### PR TITLE
FIXES meatman limb duplication glitch

### PR DESCRIPTION
**Pull request by SmoSmoSmoSmok**
## About The Pull Request

 meatmen can no longer infinitely generate meat when sawing off their limbs

## Why It's Good For The Game

 i found another unrelated  bug where beefmen can stand on 0 legs after they saw off their legs. 
HAPPENS at random IDK whats causing it
## Changelog

:cl:

/:cl:

### CODE REVIEW

**Comment by OneAsianTortoise** [comment]
Smokey nerfing himself

**Comment by SmoSmoSmoSmok** [comment]
> Smokey nerfing himself

I need TO give the current generation some fighting chance against me

**Comment by SpaceDragon00** [comment]
> i found another unrelated bug where beefmen can stand on 0 legs after they saw off their legs.

> HAPPENS at random IDK whats causing it

I fixed this bug when it was happening to digi lizards, but knowing Beefmen there's probably some snowflake code that is causing it to resurface. Or who knows maybe my fix wasn't as universal as I intended it to be

The original problem came from the "number of legs" variable (Whatever its called) being less than 0, or somehow more than 0 when they had 0 legs. If I had to guess, some part of Beefman code manually adjusts that variable instead of using the method that ensures it doesn't go below 0

**Comment by OneAsianTortoise** [comment]
> > Smokey nerfing himself
> 
> I need TO give the current generation some fighting chance against me 

We should up to 2% to 50% then

**Comment by SmoSmoSmoSmok** [comment]
> > i found another unrelated bug where beefmen can stand on 0 legs after they saw off their legs.
> 
> > HAPPENS at random IDK whats causing it
> 
> I fixed this bug when it was happening to digi lizards, but knowing Beefmen there's probably some snowflake code that is causing it to resurface. Or who knows maybe my fix wasn't as universal as I intended it to be
> 
> The original problem came from the "number of legs" variable (Whatever its called) being less than 0, or somehow more than 0 when they had 0 legs. If I had to guess, some part of Beefman code manually adjusts that variable instead of using the method that ensures it doesn't go below 0

OK i fixed it. num_legs was updating correctly but usable_legs wasnt for some reason. the glitch would happen everytime you tore off a disabled limb

**Pull request merged**
