### PR TITLE
Fuck it. *Unrecipies your hulk*

### PR DESCRIPTION
**Pull request by FernandoJ8**
## About The Pull Request

Fixes your game.

## Why It's Good For The Game

Allow me to demonstrate with a graph
Untitled

You're welcome

## Changelog
:cl:
fix: hulk could be made for some reason, now they can't. 
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
bad.

**Review by SgtHunk — CHANGES_REQUESTED** [review]
This does not meet our modularization standards.

**Comment by Helianthus00** [comment]
As much as I hate hulk, I don't think it should be completely removed from the game, nor do I think a tg edit is worth it here. If you find some way to lock it behind traitor, and emagged console, or requiring RD's ID to print, you should pr it upstream.

**Comment by remove32** [comment]
yeah as much as i hate hulk this is a bad way to address it lol

**Pull request closed without merging**
