### PR TITLE
Overhauls (most of) Heliostation Security

### PR DESCRIPTION
**Pull request by SgtHunk**
## About The Pull Request

Reworks most of the Helio Brig to not be as bland and simple (5 tile wide long hallway with way too much space)
This meant moving the Vault to departures and shrinking chem lab + customs a bit
I'm not doing Perma simply because it's way too much work to do, and I'll come to it later or someone else can do it, as it'd require reworking the entire area instead of just re-decal'ing
Credits to Reina for letting me use their Helio2 Det office

imagen

## Why It's Good For The Game

Awesome Brig is awesome??

## Changelog

:cl:
qol: Security is now more accurate at hitting disabler shots and chasing prisoners in the Heliostation Brig
/:cl:

### CODE REVIEW

**Comment by Cass-Bitchcoin** [comment]
What do you mean this shrinks chemlab? There are no screenshots of that part of the station.

**Comment by SgtHunk** [comment]
> What do you mean this shrinks chemlab? There are no screenshots of that part of the station.

You can always look at MapDiffBot

But chem lab lost 2 vertical turfs, resulting in 26 less tiles
Which means chem lab now has 202 tiles of usable space, instead of 228.

**Comment by maxspells** [comment]
chemlab

**Comment by Cass-Bitchcoin** [comment]
Why not move the two rows to the top and shift the smoke room up to accommodate them?

**Comment by SgtHunk** [comment]
If you're that eager to have 26 more tiles on one of the biggest chem labs, you can PR it after this gets merged.

**Pull request merged**
