### PR TITLE
Gives ERT clown commander's modsuit waddle module

### PR DESCRIPTION
**Pull request by OneAsianTortoise**
## About The Pull Request
**Gives ERT clown commander waddle module**

## Why It's Good For The Game
You are the commander of ERT clown. You have a mk-honk combat shoes under your modsuit. Your modsuit's shoes look like clown shoes. Yet despite all of these, you don't have waddle module, and don't waddle with modsuit on. Failure.
image

## Changelog

:cl:
expansion: Gives ERT clown commander waddle module.
/:cl:

### CODE REVIEW

**Comment by OneAsianTortoise** [comment]
Awesome check fail

**Comment by JohnFulpWillard** [comment]
fix your linters

**Comment by OneAsianTortoise** [comment]
I love it when my 1 line PR having some weird `Runtime in stack_trace.dm` and shit I don't understand.

**Comment by OneAsianTortoise** [comment]
Yeah, no. I cannot figure out the solution, nor do I want to put the module separately inside the backpack. Me dum. I am closing this.

**Pull request closed without merging**
