### PR TITLE
Fulp 3.0

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Moves a ton of things around
Makes nightmares use the same things Races do so its no longer on spec_life
Makes shuttles and ruins modular
Makes our folders easier to go through
Adds a readme to the mapping folder.

### CODE REVIEW

**Comment by SpaceDragon00** [comment]
John asks me to tgu and first thing he does is delay it with fulp 3.0 wtf..........

**Comment by JohnFulpWillard** [comment]
> 
> 
> John asks me to tgu and first thing he does is delay it with fulp 3.0 wtf..........

no I asked if you were doing so I can do it instead ( i am better than you )

**Comment by SpaceDragon00** [comment]
You can do it if you want to I will accept any opportunity to do less work B)

**Comment by Cookhimself** [comment]
Tgu my beloved

**Comment by Pepsilawn** [comment]
image

**Pull request merged**
