### PR TITLE
beefman real canon lore

### PR DESCRIPTION
**Pull request by SmoSmoSmoSmok**
## About The Pull Request

 this is the most fanstatic lore . as a befman main  i can testify this is the real lore this is my real upbringing and  the other PRs are liars and any1 who dislikes this lore is a truth denier 

## Changelog

:cl:
add: fantastic lore
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
This is the worst one

**Comment by SmoSmoSmoSmok** [comment]
> This is the worst one

u DONT know good storytelling if it hit u inth face so how about i hit u in the face instead

**Comment by Pepsilawn** [comment]
Better than willards

**Comment by OneAsianTortoise** [comment]
"this is the best lore u have ever read"

@SmoSmoSmoSmok , done.

**Pull request closed without merging**
