### PR TITLE
Helio fixes

### PR DESCRIPTION
**Pull request by Sadboysuss**
## About The Pull Request
bug fixes. All in the changelog
Screenshots:
image
## Changelog
:cl:
fix: AI upload sightlines and SMES, Tesla Layers in SM
/:cl:

### CODE REVIEW

**Comment by Horatio22** [comment]
I am not merging any changes on Helio as there is already a rework in progress.

**Comment by Horatio22** [comment]
Wait, this is the bug fix one. Remove the airlocks please as they aren't necessary.

**Comment by Sadboysuss** [comment]
Edited to reflect latest commit

**Comment by Horatio22** [comment]
I disagree with removing the maintenance EVA. The only other thing in this PR is the window change which isn't.

**Pull request closed without merging**
