### PR TITLE
Modularizes a ton of Fulp edits within TG code

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Modularizes Fulp chain of command
Modularizes Fulp job icons
Modularizes Fulp crew monitors
Modularizes Bloodsucker HUDs (Something I've wanted to do for months now but was too scared to touch the code in fear of breaking it)
Modularizes Mentorhelp
Modularizes Beefmen accessory datums

### CODE REVIEW

**Comment by Helianthus00** [comment]
I still think it is stupid that RD gets captainship before HoS but oh well. I'll talk about this with the other admins to see what they think about removing it.

**Comment by Helianthus00** [comment]
After discussing this with the other admins, we don't want to use tg's chain of command. Please keep our edit for that, as unpleasant as an edit is.

**Comment by remove32** [comment]
tg chain of command makes no sense to me 

modularize modularization when

**Comment by JohnFulpWillard** [comment]
> 
> 
> tg chain of command makes no sense to me
> 
> modularize modularization when

ITS FINE WE'RE USING FULP CHAIN OF COMMAND ITS GOOD I MADE IT MODULAR ITS FI

**Pull request merged**
