### PR TITLE
readds security borgs

### PR DESCRIPTION
**Pull request by SmoSmoSmoSmok**
## About The Pull Request

 READDS secURITY CYBORGS FOR  INFIL SELF FACTION OBJECTIVE goddamn U HAVE A BLUESPACE bomb YOU NEED TOPLANT IT INA LOCATIO NTHIS BOMB OPENS UP A BLUESPACE PORTAL AND ANGRY SECURITY CYBORGS COME OUT OF THE PORTAL THEYRE PISSED OFF AT NANOTRASEN FOR DECOMISSIONING THEM they are ON A PATH OF REVENGE AGAINST NANOTRASEM  they ARE TASKED with HELPING THE INFILTRATOR witH his objectiveS. GHOSTS can CLICK THE PORTAL TO become THE SECURITY CYborgs (only a maximum of 2 ghosts)  THE CYBORGS COME OUT OF THE PORTAL LIKE THE TERMINATOR WHEN HE CAME OUT Of THE PORTAL you FEEL ME???

## Changelog

:cl:
/:cl:

### CODE REVIEW

**Comment by StoneMason** [comment]
do they throw their shit

**Comment by ReinaCoder** [comment]
ur so brave .. y arent i being pinged as codeowner hello?

**Comment by OperativeLyn** [comment]
Mothmandayo Smokey are you ok please answer me

**Comment by SmoSmoSmoSmok** [comment]
FIRSt off its mud

**Comment by SmoSmoSmoSmok** [comment]
second, I am brock lesnar

**Comment by OneAsianTortoise** [comment]
can we repo ban this guy?

**Comment by SgtHunk** [comment]
Add more commits by pushing to the [WRQ09E90QJEJ9Q2EWRQ09E90QJEJ9Q2EWRQ09E90QJEJ9Q2EWRQ09E90QJEJ9Q2EWRQ09E90QJEJ9Q2EWRQ09E90QJEJ9Q2EWRQ09E90QJEJ9Q2E](https://github.com/SmoSmoSmoSmok/fulpstation/tree/WRQ09E90QJEJ9Q2EWRQ09E90QJEJ9Q2EWRQ09E90QJEJ9Q2EWRQ09E90QJEJ9Q2EWRQ09E90QJEJ9Q2EWRQ09E90QJEJ9Q2EWRQ09E90QJEJ9Q2E) branch on [SmoSmoSmoSmok/fulpstation](https://github.com/SmoSmoSmoSmok/fulpstation).

**Comment by wraith-54321** [comment]
I would say make the borgs have no laws but give them some kind of unique objective, not sure if that would work with server policy though so maybe not.

**Pull request merged**
