### PR TITLE
Makes round time actually work somewhat

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

this is a bandaid but server time starts at 19 hours and actually increments now.

It looks like 514/515 changed how time and suchs works and would require a lot more work than I'm willing to put into it rn.

### CODE REVIEW

**Comment by remove32** [comment]
would... would giving it a -19 offset "fix" the problem?

**Comment by JohnFulpWillard** [comment]
did that now

**Comment by RealityOverseer** [comment]
Sir that did not fix it
image
proc/station_time minuses the offset, which means you are actually adding 19 hours.
proc/time_to_twelve_hour also minuses the offset.
At least that's what I think is causing the time to appear like above.

**Comment by remove32** [comment]
i hate DST i hate DST i hate DST i hate DST i hate DST

**Pull request merged**
