### PR TITLE
Jerseyhead Costume For Halloween Beacon

### PR DESCRIPTION
**Pull request by BoltonsHead**
## About The Pull Request
It's a jerseyhead costume, and it works. All coded out, all tested, it's workin baby!
## Why It's Good For The Game
add: Jerseyhead halloween costume
## Changelog
:cl:
add: Jerseyhead halloween costume to the halloween beacon.
/:cl:

### CODE REVIEW

**Comment by GuillaumePrata** [comment]
I'm happy you got all the code working but it's a little early to add Halloween costumes and we shouldn't add costumes into previous years events.

**Comment by BoltonsHead** [comment]
> I'm happy you got all the code working but it's a little early to add Halloween costumes and we shouldn't add costumes into previous years events.

Guill, I'm willing to shift the date to 2021, but it was simply added for convenience. Costumes that you can buy in bulk like in the Halloween beacon are much more appealing than buying one part after another. If you do have any other suggestions for where it can go, do tell me.

**Comment by HugoOdaX** [comment]
He coded it...

**Comment by BoltonsHead** [comment]
> > I'm happy you got all the code working but it's a little early to add Halloween costumes and we shouldn't add costumes into previous years events.
> 
> Guill, I'm willing to shift the date to 2021, but it was simply added for convenience. Costumes that you can buy in bulk like in the Halloween beacon are much more appealing than buying one part after another. If you do have any other suggestions for where it can go, do tell me.

Nevermind, it'll come next halloween.

**Comment by Helianthus00** [comment]
> Nevermind, it'll come next halloween.

So I'm confused on this. Do you want it merged or do you mean that you don't want it merged for now?

**Pull request closed without merging**
