### PR TITLE
Fixes capitalization inconsistencies with var-editing items on helio

### PR DESCRIPTION
**Pull request by Horatio22**
## About The Pull Request

Fixes Helio's capitalization inconsistencies with all the var-edited stuff. /tg/'s style only capitalizes proper nouns, but every one of Helio's var-edited things has capital letters.

## Why It's Good For The Game

Having certain things var-edited to be capitalized looks sloppy when everything else is lower case. It should be uniform. 

## Changelog
:cl:
fix: minor fixes on Helio
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
the TG Update https://github.com/fulpstation/fulpstation/pull/58 is changing a lot for Heliostation, should've waited for that PR to get merged first

**Comment by Helianthus00** [comment]
make a PR updating everything to be capitalized there instead.

**Comment by CyoTheProtogen** [comment]
you forgot to fix the moth plushie

**Comment by Horatio22** [comment]
> 
> 
> you forgot to fix the moth plushie

Fuck, I'll go back in and fix that. Thanks!

**Comment by remove32** [comment]
mfw (my face when ) repo blacklisted from MDB (map diff bot) so [REDACTED]

**Pull request closed without merging**
