### PR TITLE
Fixes Malkavian admin loggings

### PR DESCRIPTION
**Pull request by Pepsilawn**
## About The Pull Request

Fixes Malkavian revelations not showing as being Forced when viewed thru ingame logs and game.log so I can't tell if I should bwoink or if John coded these slurs in, also makes it annoying to filter out game.log with Notepad++ when I should be able to hide lines containing "FORCED". Only works with Malkavian revelations that aren't whispered until my fix PR is merged on tg and we tgu but it wouldnt require any extra changes to this code once thats done so i might aswell PR this now.

## Why It's Good For The Game
image

Ugly and cannot be filtered out with Notepad++ easily, I will not read your game logs. 😢 

## Changelog
:cl:
admin: Malkavian revelations are now logged correctly.
/:cl:

### CODE REVIEW

**Comment by SgtHunk** [comment]
☹️

**Comment by Sheits** [comment]
?

**Comment by Sheits** [comment]
idc

**Comment by Pepsilawn** [comment]
can you guys get out of my pr

**Comment by JohnFulpWillard** [comment]
admins getting flooded with shitty unrelated logs is a feature because I had admins

**Pull request merged**
