### PR TITLE
Beefmen Now Take 20% Extra Damage Instead of 2%

### PR DESCRIPTION
**Pull request by SpaceDragon00**
## About The Pull Request

Just updates the armor value to its intended value

## Why It's Good For The Game

Hate these disgusting little guys

## Changelog

:cl:
fix: Beefmen now correctly take 20% more damage
/:cl:

### CODE REVIEW

**Comment by SpaceDragon00** [comment]
mfw I create a branch off of fulpstation master and my branch is not based off of fulpstation master

**Comment by SmoSmoSmoSmok** [comment]
I hope ur checks never pass and UR pc explodes and blwos ur fat fingers off

**Comment by JohnFulpWillard** [comment]
K

**Comment by SpaceDragon00** [comment]
> I hope ur checks never pass and UR pc explodes and blwos ur fat fingers off

Its ok there'll probably be another bug that causes them to take less damage than usual

**Pull request merged**
