### PR TITLE
Moves beefmen traumas to the brain, fixes suits

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Fixes the jumpsuit offset so they properly fit on Beefmen Moves beefmen traumas to their brain, which is now in the DME

Look at this guy
image

## Why It's Good For The Game

This might help with https://github.com/fulpstation/fulpstation/issues/968 - But it fixes actual bugs too, and makes beefmen use TG system more rather than snowflaking it.

## Changelog

:cl:
code: Beefmen traumas are now tied to their brain.
fix: Beefmen jumpsuits now properly fit them.
/:cl:

### CODE REVIEW

**Review by SgtHunk — COMMENTED** [review]
I'd appreciate if you could remove a bunch of traits on beefmen because half of them are handled by organs (literate and such)

**Comment by JohnFulpWillard** [comment]
Why didn't screenshot test catch this PR I literally changed how Beefmen look

**Comment by JohnFulpWillard** [comment]
image

**Comment by SgtHunk** [comment]
imagen

**Comment by remove32** [comment]
re-running the CI didn't fix the bad comparison check, but since we know it's there i dont think we need to have that passing to move forward.

**Comment by JohnFulpWillard** [comment]
The fix is https://github.com/fulpstation/fulpstation/pull/969

**Pull request merged**
