### PR TITLE
fixes rabbits being non-hostile

### PR DESCRIPTION
**Pull request by SmoSmoSmoSmok**
## About The Pull Request
also removes time constraint from the ruleset i didnt mean to leave that in

## Changelog
:cl:
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
They aren't neutral in normal MH gameplay because they copy the factions of their creators. It's only non-hostile when Admin spawned.

**Comment by SmoSmoSmoSmok** [comment]
> They aren't neutral in normal MH gameplay because they copy the factions of their creators. It's only non-hostile when Admin spawned.

asshole admin tried spawning 100 of them for eorg and told me theyre broken

**Comment by SmoSmoSmoSmok** [comment]
i guess theres no harm in giving them a default faction

**Comment by JohnFulpWillard** [comment]
> asshole admin tried spawning 100 of them for eorg and told me theyre broken

staff report them for trying to crash the server with 100 explosions

**Comment by JohnFulpWillard** [comment]
also it's funny they complained to you in a place I cannot see for a thing I did

**Pull request merged**
