### PR TITLE
Helio Sci Rework

### PR DESCRIPTION
**Pull request by SgtHunk**
## About The Pull Request
Hi, check mdb

## Why It's Good For The Game

its cool

## Changelog

:cl:
add: Helio Sci Rework
/:cl:

### CODE REVIEW

**Comment by SgtHunk** [comment]
imagen

**Review by Pepsilawn — COMMENTED** [review]
Robotics missing the mech removal crowbar cabinet will further review when I have the time

**Comment by OneAsianTortoise** [comment]
My review

**Comment by KittyNoodle** [comment]
why does sec have an exosuit control console in their post?

**Pull request merged**
