### PR TITLE
Adds a Pubby Courtroom

### PR DESCRIPTION
**Pull request by Cure221**
## About The Pull Request
image
now with 11% less issues
## Changelog
:cl:
add: Adds a court room to pubby

/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
YOU CAN'T REMOVE THE DISPOSAL CHUTE THAT GOES TO CARGO

**Comment by Cure221** [comment]
> YOU CAN'T REMOVE THE DISPOSAL CHUTE THAT GOES TO CARGO

YOU CANNOT STOP ME

**Comment by Horatio22** [comment]
The siding decals look a little out of place with the rest of the map when every other room uses either the single tile or contrasted decals. Would you mind switching these out for something that is a bit more cohesive with the other areas?
image

**Comment by Cure221** [comment]
I switched them to yellow contrasted
image

**Comment by Horatio22** [comment]
One more little nitpick, but can you give the tool storage a disposal bin? A disposal bin going from the hall(?) to tool storage is part of Pubby's soul, I am told.
image

**Comment by Cure221** [comment]
> The decals look much more cohesive now - thanks! One more little nitpick, but can you give the tool storage a disposal bin? A disposal bin going from the hall(?) to tool storage is part of Pubby's soul, I am told. image

i did add one there but it looked weird because it was infront of the medkit/toolbelt table, i can remove that table and replace it with a disposal chute

**Comment by Cure221** [comment]
image
 pubby's soul is back

**Review by JohnFulpWillard — APPROVED** [review]

**Comment by JohnFulpWillard** [comment]
if the closet has judge stuff then you gotta take it out of law office maints

**Comment by Cure221** [comment]
> if the closet has judge stuff then you gotta take it out of law office maints

fixed

**Pull request merged**
