### PR TITLE
Adds HoochMaster Pubbystation's Bar

### PR DESCRIPTION
**Pull request by ackbarscrowbars**
## About The Pull Request

**Adds a HoochMaster Deluxe** (Bar variant of CondiMaster/ChemMaster) **to the Pubbystation Bar**, adds a 2nd Bar Requests Console in Bar Storage (Next to the double-barreled shotgun), moves around most of the wall-mounted stuff in the Bar (Newscaster, Request Console, Intercom, Fire Alarm), and adjusts the Light switch's X/Y position a little. No changes to the Lounge.

## Why It's Good For The Game

This tweaks the layout of the wall-mounted objects in a mildly more appealing manner, as well as adding a HoochMaster Deluxe, which Pubby's bar **doesn't have**. This forces the Bartender(s) to take or build a ChemMaster or equivalent machine if they want to make cocktails of any complexity. I also believe the storage room could use an additional request console. If nothing else, it's a little extra clutter.

## Changelog

:cl:
add: Adds a HoochMaster Deluxe (Bar variant of CondiMaster/ChemMaster) to the Pubbystation Bar!
add: Adds 2nd Bar Requests Console in Bar Storage (Next to the double-barreled shotgun)
qol: Moves the Newscaster, Request Console, Fire Alarm, and Intercom to new positions on the Bar's walls
/:cl:

### CODE REVIEW

**Comment by ackbarscrowbars** [comment]
bar
storage

**Review by SgtHunk — CHANGES_REQUESTED** [review]
use the appropiate subtype for the firealarm, as that one has it's direction varedited

**Comment by ackbarscrowbars** [comment]
> use the appropiate subtype for the firealarm, as that one has it's direction varedited

The fire alarm is like that with pubby to begin with, I only put it in a different place. 
I don't understand the problem. Does it cause any issue?

**Comment by SgtHunk** [comment]
> The fire alarm is like that with pubby to begin with, I only put it in a different place. 
> I don't understand the problem. Does it cause any issue? 

It wasn't like that in the first place, it was an edit you made (as shown in files changed).
It causes issues, both in mapping standards and when futureproofing certain projects like wallening
In an ideal world, there shouldn't be varedits in maps and the TG codebase slowly tries to reach that goal

**Review by SgtHunk — APPROVED** [review]

**Pull request merged**
