### PR TITLE
Helio update

### PR DESCRIPTION
**Pull request by Sadboysuss**
## About The Pull Request
removed free space suit and jetpack in maints, added firelocks to arrivals, fixed AI upload sightlines making turrets fire on bystanders in the hall.
## Why It's Good For The Game
bug fix, space suit is abused by antags, firelocks for more safety
screenshots: 

image
image
image

## Changelog
:cl:
add: Firelocks in arrivals
balance: removed free space suit and jetpack room in maints, replaced it with a maints garden.
fix: AI upload sightlines
fix: fixed SMES and Tesla coil layers in SM room to default.

/:cl:

### CODE REVIEW

**Comment by Pepsilawn** [comment]
Abandoned EVA storage isnt EVA if theres no EVA if youre gonna remove the suit you should fix it so it still makes sense

**Comment by SgtHunk** [comment]
abandoned eva with no eva... fucked up

**Comment by Sadboysuss** [comment]
edited to reflect latest commits

**Review by SgtHunk — CHANGES_REQUESTED** [review]
I'd appreciate if you could atomize these changes.
i.e make the balance changes on a PR, and the fixes on another.
This is to ease the process as there has to be more conversation behind any balance change than there is just merging a fix.
The maintainer consesus right now: the fixes here are fine, the balance change on the maint room is an overreaction and this maint room was already done on service maints.

**Comment by Horatio22** [comment]
Just a list of bad changes. Different =! good.

**Pull request closed without merging**
