### PR TITLE
Aspen Moth Wings

### PR DESCRIPTION
**Pull request by Greniza**
## About The Pull Request

New moth wings: Aspen. Based on Aspev's Chemistry Moth drawing.

Now you can cosplay as Chem Moff properly!
image

## Why It's Good For The Game

Extra moth customization:
image

## Changelog
:cl:
imageadd: New moth wings and antennae, Aspen.
/:cl:

### CODE REVIEW

**Comment by Greniza** [comment]
If the wings are a touch flat, let me know and I'll get on it.

**Comment by JohnFulpWillard** [comment]
👎 because you used 'moff' unironically.
otherwise it's good.

**Comment by Greniza** [comment]
> 👎 because you used 'moff' unironically.
> otherwise it's good.

willard.

the name of the image file created by aspev is "chemmoff".

i am quoting them directly.

**Comment by JohnFulpWillard** [comment]
> 
> 
> > 👎 because you used 'moff' unironically.
> > otherwise it's good.
> 
> willard.
> 
> the name of the image file created by aspev is "chemmoff".
> 
> i am quoting them directly.
> 
> you can see this by mousing over the image on the archive on the [forum](https://forum.fulp.gg/t/aspevs-art-archive/1746)

don't care plus you use 'moff' unironically

**Comment by Greniza** [comment]
> > > 👎 because you used 'moff' unironically.
> > > otherwise it's good.
> > 
> > 
> > willard.
> > the name of the image file created by aspev is "chemmoff".
> > i am quoting them directly.
> > you can see this by mousing over the image on the archive on the [forum](https://forum.fulp.gg/t/aspevs-art-archive/1746)
> 
> don't care plus you use 'moff' unironically

when

**Pull request merged**
