### PR TITLE
Separates Heliostation's  Aft Surgery into two separate rooms.

### PR DESCRIPTION
**Pull request by maxspells**
## About The Pull Request

helio surgery
## Why It's Good For The Game
I really love having separate rooms for surgeries. The smartfridge is in the center of the room so it can be used by either side. Each room has shutters that can can be closed for privacy. I moved the wall into the security room a bit so I had to slightly redesign it and remove the chairs, but other than that everything is mostly unchanged. Playtested it and everything seemed to work fine, but this is my first map PR so I'm sure there's probably something I missed.

### CODE REVIEW

**Comment by Pepsilawn** [comment]
Surgerya requires access but not surgeryb?

**Comment by Pepsilawn** [comment]
You also didnt edit your cameras

**Comment by maxspells** [comment]
Thanks, looking into fixing those now!

**Comment by Pepsilawn** [comment]
Camera name doesn't matter what you're looking for is the c_tag, also needs to be added to medbay's network

**Comment by Pepsilawn** [comment]
Why are we using blast doors instead of shutters

**Pull request merged**
