### PR TITLE
Removes bloodsuckers

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

shit antag

## Why It's Good For The Game

shit antag

## Changelog

:cl:
del: vampires
/:cl:

### CODE REVIEW

**Comment by Pepsilawn** [comment]
Ur supposed to edit the dme

**Comment by Sheits** [comment]
DEL VAMPIRES?????? I WIN BITCH

**Comment by Greenfire575** [comment]
but like
why?

**Comment by JohnFulpWillard** [comment]
> but like why?

it's bad + no one bothers to fix it

**Comment by JohnFulpWillard** [comment]
this pr closes https://github.com/fulpstation/fulpstation/issues/676

**Comment by ReinaCoder** [comment]
they arent vampires

**Comment by JohnFulpWillard** [comment]
I feel I should explain myself;
I decided to close this pull request because I had realized something very important. Bloodsuckers is actually the single greatest, sole good antagonist to ever exist on Fulpstation. Its removal would devastate the community and likely even kill the server as a whole. This antagonist is required for the survival of Fulpstation, and as such I feel we should not remove such an important antagonist.

**Pull request closed without merging**
