### PR TITLE
solitaire arrivals fixes + maint loot removal

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Fixes some problems with Solitaire's new arrivals, and cuts back on some maint look in arrival/brig maintenance, since I found it too much.

### CODE REVIEW

**Comment by Pepsilawn** [comment]
this doesnt fix the apc issue i posted about in the first pr i hate you

**Comment by Pepsilawn** [comment]
image
these arent linked to anything

**Comment by JohnFulpWillard** [comment]
> this doesnt fix the apc issue i posted about in the first pr i hate you

i completely forgot about it you commented it while i was at work

**Comment by Pepsilawn** [comment]
image
area leaks into space

image
vault copypasted without changing the piping, cables and the cyclelink helper's dir

image
flying wall gizmos

image
broken disposal piping

image
broken disposal piping

also would be cool to fix the roundstart AT in the N2O room above holodeck I think pucci fixed that before

**Pull request merged**
