### PR TITLE
w

### PR DESCRIPTION
**Pull request by tommysalami3**

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
w

**Comment by ATH1909** [comment]
w

**Comment by tommysalami3** [comment]
HAHAHAHAHAHA WHEN DID THIS HAPPEN

**Comment by tommysalami3** [comment]
image

**Comment by SgtHunk** [comment]
grudgecode

**Comment by JohnFulpWillard** [comment]
pointless bloat

**Pull request closed without merging**
