### PR TITLE
adds armoury shutters to pubbystation armoury

### PR DESCRIPTION
**Pull request by SmoSmoSmoSmok**
## About The Pull Request

i had to like, move some things around to make the shutter fit

## Why It's Good For The Game

Ea

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
expansion: Expands content of an existing feature
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by StoneMason** [comment]
gate smokey's pr's until he does the changelogs with the initial commit

**Comment by SgtHunk** [comment]
armory** please stop being british.

**Comment by Lyn505** [comment]
Smokey make a changelog challenge (impossible)

**Comment by SmoSmoSmoSmok** [comment]
englisj is like my 3rd language FUCK you native englsh speakers for complicating things

**Comment by Nobelium-XVIII** [comment]
Make a changelog

**Pull request merged**
