### PR TITLE
Late September TGU: Bitrunning and other stuff probably

### PR DESCRIPTION
**Pull request by Momo8289**
## About The Pull Request
My first TGU but everything seems to be good, needs to be test merged, obviously. I did my best with mapping in bitrunners on helio, selene, and pubby, but if anyone wants to improve them, be my guest. 
## Why It's Good For The Game
erm
## Changelog
:cl:
add: September TGU
/:cl:

### CODE REVIEW

**Comment by OneAsianTortoise** [comment]
Hamburger

**Comment by Momo8289** [comment]
Only failing test are TG's fault, and they've already removed them in a PR that was merged right after I did the TGU

**Comment by Pepsilawn** [comment]
> Only failing test are TG's fault, and they've already removed them in a PR that was merged right after I did the TGU

Port it so we arent stuck with defective unit tests for an entire month

**Comment by Momo8289** [comment]
> > Only failing test are TG's fault, and they've already removed them in a PR that was merged right after I did the TGU
> 
> Port it so we arent stuck with defective unit tests for an entire month

Guh

**Pull request merged**
