### PR TITLE
deletes cyberbliss and aspen wings

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

We recently had to go into our files and delete some moth wings/antennaes/markings, as TG ported them from us, so I took the opportunity to also delete unwanted/unused moth wings that didn't fit the 'moth' theme; Cyberbliss and Aspen.

### CODE REVIEW

**Comment by StoneMason** [comment]
hey why dont you resprite them :)

**Comment by SpaceDragon00** [comment]
I understand you're john willard, so this PR is going to get merged no matter what, but could you at least try to be less of an ass about it? Like, at least pretend you need to make a real PR to remove whatever sprites you don't like, not a single sentence that doesn't even mention half the changes you made. 

A lot of Fulpstation sprites are from community events, which are designed to help get new people into spriting, so turning around as a staff member and saying shit like "Your sprites don't look good at all" after people asked me to not only ADD these, but after they got MERGED is just super fucking shitty. 

I didn't want to add my sprites at first, but encouragement from Guil is what made me give Greniza the go-ahead to adapt them. I was still scared of it, because I didn't want something I worked hard on to be trashed by random players, but I did it because it seemed like they wanted it. And after all of that, I turn around, and it's a fucking moderator telling me my sprites are irredeemably bad? I can't even imagine how this would feel from people who don't even fucking know you like I do. 

Like, are you genuinely going to pretend you run a server that welcomes new contributors with spriting events, while bashing them for their efforts that you asked for, encouraged, and added? Are you genuinely going to walk around as a "Moderator" in the community, trashing people's work because they dared do something while being encouraged by an admin? 

You aren't a random goddamn github commentor, you're a staff member interacting with the work of people you know, people who are going to see this. You're interacting with the work of people you know are beginners, and don't know well enough to say how they'd react to this. Why do you think it's okay to act like such an ass while in your position?

Not to mention, these sprites weren't even grandfathered in from an ancient PR. They were added 6 fucking months ago. Why would the maintainers change their minds now, besides the fact that you're the person asking?

**Comment by JohnFulpWillard** [comment]
The sprites are being removed because it was something I wanted to remove for a while, but never got around to until TG ported some of our sprites, forcing us to go back and remove what they ported over. It was said the pride moth wings looked way too bright when they were originally added, and they were never changed, so if they weren't gonna be improved, I don't see any reason to keep them.
I kept two of the moth wings because I saw/still see players in-game that frequently use them, compared to Aspen/Cyberbliss, which I haven't seen used in a long time. Maybe the antennae for Aspen is used, but that's as much use as they get.

I also am against bringing a status I have with the server on the repository, being a moderator there never gave me any special privileges here, I've been doing this since before I was even a Contributor. Same reason I never bring my staff status on any other repository I contribute to, because it's irrelevant. There's always some separation between the codebase and the server when open-source is involved.

I also leave PR bodies mostly empty because most of what I have to say about stuff, is already said in the contributor channel, so any maintainer would already see it there. Most PR bodies I have on the fulp repo, are just barebone sentences I throw in because the discussion for them has already been had or can be had in the contributor channel.

**Comment by Sheits** [comment]
i really like these wings wtf

**Comment by Sheits** [comment]
would you like me to have a look at them?

**Pull request closed without merging**
