### PR TITLE
Resprites fulpstation food to be consistent with the tg upstream.

### PR DESCRIPTION
**Pull request by tommysalami3**
## About The Pull Request

Makes sausage bread look similar to the appearance of current bread sprites. Tweaks the egg on sausage and eggs.

## Why It's Good For The Game

Sausage breads the only bread still using the old sprite.

## Changelog

:cl:
:imageadd: Resprites sausage bread and sausage and eggs.
/:cl:

### CODE REVIEW

**Comment by tommysalami3** [comment]
image
bread!!!

**Comment by Helianthus00** [comment]
You'll need to remove the plate from the sausage and eggs sprite, but these look great otherwise. Though I will miss the goofy sausage bread sprite.

**Comment by tommysalami3** [comment]
image
the beast has been slain

**Comment by JohnFulpWillard** [comment]
i hate the food update and i wish it was PR'ed to TG instead.

Though, very good sprites

**Pull request merged**
