### PR TITLE
Revert "Reina contributing and its consequences have been a disaster for the human race"

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
Reverts fulpstation/fulpstation#408

This is the stupidest grudgecoded PR merged under 24 hours by the delusional host, ever. Helianthus, the Fulpstation Host, thinks they know what’s best for the server, when they clearly fuckin don’t. They are so out of touch with the playerbase that the only way they can push changes onto the players is to force change onto them before they even realize what’s going on, preventing any chance at resistance by the players. This is terrible and breeds a shitty and authoritative community, and must be stopped if this codebase plans to be taken seriously in any way.

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
So True

**Comment by wraith-54321** [comment]
You know, I cant tell if this is a joke or not, and frankly, I dont really care

**Comment by LemonInTheDark** [comment]
Wait this isn't a joke?

**Comment by JohnFulpWillard** [comment]
> Wait this isn't a joke?

it is a joke.

**Comment by LemonInTheDark** [comment]
so true

**Comment by Helianthus00** [comment]
John willard (contributor at fulpstation) dragging my image through the mud yet again...

**Pull request closed without merging**
