### PR TITLE
Pubby transit tube edits

### PR DESCRIPTION
**Pull request by QuiteLiterallyAnything**
## About The Pull Request
This pull request replaces Pubby Station's transit tube stations with transit tube dispensers. Additionally, this PR adds grilles around most of Pubby's transit tube networks.
## Why It's Good For The Game
Transit tube stations require you to wait for a singular transit tube to make its rounds across an entire network. Transit tube dispensers eliminate this rather tedious waiting time by simply dispensing a temporary transit tube for. . . well. . . _transit_.

The only advantage of transit tube stations (at least to my knowledge,) is that they prevent people from attempting to cross a broken transit tube network. That is why this PR also adds protective grilles around most of Pubby's transit tube networks.
## Changelog
:cl:
qol: Replaced Pubby Station's transit tube stations with transit tube dispensers
add: Added grilles around some of Pubby's transit tube networks
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
sad!

**Comment by QuiteLiterallyAnything** [comment]
> sad!

Pardon? I don't quite understand what you mean—

**Comment by OneAsianTortoise** [comment]
> > sad!
> 
> Pardon? I don't quite understand what you mean—

You can just ignore him don't worry.

**Comment by QuiteLiterallyAnything** [comment]
> > > sad!
> > 
> > 
> > Pardon? I don't quite understand what you mean—
> 
> You can just ignore him don't worry.

Okay    ._.

**Comment by Pepsilawn** [comment]
Not too fond of the new grilles placement and how they're hugging the whole thing

**Comment by QuiteLiterallyAnything** [comment]
> Not too fond of the new grilles placement and how they're hugging the whole thing

Appropriate changes have been made.

**Pull request merged**
