### PR TITLE
[Ready for TM] Space Box Station

### PR DESCRIPTION
**Pull request by urococt**
## About The Pull Request

* Merges Box with Ice Box
 * Re-adds the gravity generator and mining shuttles
 * Replaces the brig's pit of death with the gas chamber
 * Removes the lowest Z level
 * Removes the mining base from the middle Z level
* Backports all relevant fixes made to Ice Box since Fulp's last pull from TG
* Fixes gravity generator and telecomms SMES wiring
* Replaces the second Z level's warehouse with a slightly modified version of Delta Station's cargo bay
* Adds a lower level to telecomms. This houses the comms relay that was in the mining base
* Replaces the Kilo mining shuttle with Box's, since the Kilo shuttle runs out of power
* Sets the base turf in cargo, botany, and xenobio to openspace, allowing things to fall through holes in the floor (this does not happen elsewhere)
* Fixes escape pods. Now all four pods can launch to lavaland

Tested on a local server. The mapping test verbs did not report any problems.

## Why It's Good For The Game

Ice Box has problems with atmos, especially since fire alarms are activated by cold temperatures now. It's also a shame to let Box die.

## Changelog
:cl:
add: Space Box Station has been added, explore the depths of space with boxstation right in the middle of it, don't forget your space suit and internals!
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
> Sets the base turf in cargo, botany, and xenobio to openspace, allowing things to fall through holes in the floor (this does not happen elsewhere)

this is an unimaginably dumb idea, either bring old box back, delete those bottom rooms or dont bother

**Comment by urococt** [comment]
Box would take more effort to port and maintain. One of the main features of Space Box is the ability to copy and paste upstream changes from Ice Box, since the interior of the station is mostly the same.

There are only four baseturf helpers. If the gimmick proves to be annoying, they can easily be removed. The idea of setting the baseturfs is to allow in-game modification of these areas to make sense in 3D space.

**Comment by Helianthus00** [comment]
Even copy-and-paste maintenance is a pain in the ass. Take it from me, I maintained regular box station by myself for a while and it was not worth it. For a major map change like this, it would either have to be entirely unique or worth manually maintaining an entire station.

**Comment by urococt** [comment]
I'm willing to maintain the map. If it breaks, just pull it out of rotation.

**Comment by urococt** [comment]
Is it possible to set the area of the escape pods? I tried setting `area_type` on the docking port, but it didn't seem to work.

It would be nice if the pods weren't all "Escape Pod One"

**Comment by Helianthus00** [comment]
As much of a pain Icebox can be, I tried this song and dance before on the old repo and I'm not going to end up responsible for this eventually. Closing.

**Comment by urococt** [comment]
ight imma head out

**Pull request closed without merging**
