### PR TITLE
[MDB IGNORE] TGU

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

IMPORTANT: For large prs, make sure include in your title [IDB IGNORE] and/or [MDB IGNORE] to keep their bots from crashing. 
MDB is especially important for large map changes
Failure to do so could result in repoban
If you need help please reach out on the discord!

### CODE REVIEW

**Comment by SgtHunk** [comment]
idc

**Comment by OperativeLyn** [comment]
@Pepsilawn Hey this dude stole your TGU PR...

**Comment by Ebb-Real** [comment]
John on his way to make beefplushie traitor item real

**Comment by JohnFulpWillard** [comment]
well i guess this isn't gonna go anywhere...

**Comment by OperativeLyn** [comment]
:sob:

**Pull request merged**
