### PR TITLE
The engineering rework that isn't Ray's (the better one)

### PR DESCRIPTION
**Pull request by Pepsilawn**
## About The Pull Request

This redoes Selene's engineering to make it feel like less of a straight hallway with rooms tacked to the sides it's honestly not a straight upgrade but I'll probably go through one or two revisions still before I'm satisfied enough

<details>
  <summary>MDB Render</summary>
  
image

</details>

### CODE REVIEW

**Comment by zzzmike** [comment]
this is a good opportunity to ask if the 'engi main door requires construction access' thing is fixed or not? because engi sec didn't have construction a couple weeks ago anyway. i think it affected selene and pubby but helio is fixed

**Comment by OneAsianTortoise** [comment]
Die

**Comment by Pepsilawn** [comment]
> hey man u forgot to decal it

Which 1

**Comment by Pepsilawn** [comment]
> > Which 1
> 
> um engi in general

Looks good to me

**Comment by SgtHunk** [comment]
> Looks good to me

Fulp map decal brainrot

imagen

**Comment by SgtHunk** [comment]
why is all of selene just "tile decal around room" this is LITERALLY just helio decals but with tile decals instead of siding

**Comment by Pepsilawn** [comment]
> why is all of selene just "tile decal around room" this is LITERALLY just helio decals but with tile decals instead of siding

Consisyencu

**Pull request merged**
