### PR TITLE
Changes the mentorhelp sound effect

### PR DESCRIPTION
**Pull request by maxspells**
## About The Pull Request
Changes out the old bikehorn sound effect for a new sound effect made by Mokoshotar.

## Why It's Good For The Game

Custom sound effects are fun. The old bike horn was easy to miss since it is a common sound effect heard in game, with the new effect mhelps will stand out a lot more.
## Changelog

:cl:
addsound: New mhelp sound effect played for mentors and admins.
/:cl:

### CODE REVIEW

**Review by JohnFulpWillard — CHANGES_REQUESTED** [review]
what

**Comment by maxspells** [comment]
> And this PR is supposed to make getting an mhelp sound not easy to miss?
Yeah and we thought it was funny to change it to someone screaming help.

**Comment by Greniza** [comment]
keep the sound effect for april first

**Comment by Sheits** [comment]
Can U make the new mhelp Mac and cheese sounds

**Comment by SgtHunk** [comment]
> sounds are just sprites for the ears

you're lucky github doesn't allow me to react with nerd emotes

**Comment by maxspells** [comment]
closing this for the time being in case anyone else wants to finish this since life just got super busy for me for the next 2-3 weeks

**Pull request closed without merging**
