### PR TITLE
Heliostation Emergency Shuttle

### PR DESCRIPTION
**Pull request by SgtHunk**
## About The Pull Request

Replaces the current Helio Shuttle with a new one seeing as, as fun as having a small helio as a shuttle, it's a bit too silly for a roundstart shuttle and also the sheer size of it breaks the 15 tile rule on the map it's supposed to be used in
This shuttle keeps the general idea of the original shuttle (Spacey, fishing, bar, etc) while looking a bit more grounded in terms of design
## Why It's Good For The Game

yea

## Changelog

:cl:
add: Helio Shuttle v2
/:cl:

### CODE REVIEW

**Comment by SgtHunk** [comment]
The shuttle in question:
imagen

**Comment by SgtHunk** [comment]
Don't ask why half the walls seem to be missing it's MDB sometimes stuff doesn't preview well on it (similarly to how the helio brig asteroid is invisible on the webmap) in-game pics soon

**Comment by SgtHunk** [comment]
(null)scrnshot1

**Comment by Pepsilawn** [comment]
This doesnt look like a miniature helio

**Comment by OneAsianTortoise** [comment]
> This doesnt look like a miniature helio

Adds ten hundred thousand donkbox and it will be exactly like heliostation

**Comment by SgtHunk** [comment]
> This doesnt look like a miniature helio

^ Made Selene Engi

**Comment by JohnFulpWillard** [comment]
barmaid in default shuttle 🐸

**Comment by SgtHunk** [comment]
> barmaid in default shuttle 🐸

imagen

**Comment by OneAsianTortoise** [comment]
> > barmaid in default shuttle 🐸
> 
> imagen
> 

Add catgirl maid cafe instead

**Pull request merged**
