### PR TITLE
Fixes some misspellings in our codebase

### PR DESCRIPTION
**Pull request by Pepsilawn**
## About The Pull Request

Someone didn't know how to spell that word and fucked it up on all our maps

## Why It's Good For The Game

Makes our maps look good?

## Changelog

:cl:
fix: fulpstation is saved
/:cl:

### CODE REVIEW

**Review by SgtHunk — APPROVED** [review]
I fucking hate the British

**Comment by JohnFulpWillard** [comment]
https://github.com/fulpstation/fulpstation/blob/c5d9bf895954f7b277f78018df50875d1daf6206/.github/guides/STYLE.md?plain=1#L405-L406

**Comment by Pepsilawn** [comment]
> from the Fulpstation.Com (brand) repository:
> 
> https://github.com/fulpstation/fulpstation/blob/c5d9bf895954f7b277f78018df50875d1daf6206/.github/guides/STYLE.md?plain=1#L402-L406

Canada is like the 2nd most british thing after britain please get out of my pull request

**Comment by JohnFulpWillard** [comment]
> Canada is like the 2nd most british thing after britain please get out of my pull request

https://en.wikipedia.org/wiki/Dual_monarchy_of_England_and_France

**Pull request merged**
