### PR TITLE
Fixes some Pubby issues.

### PR DESCRIPTION
**Pull request by OperativeLyn**
## About The Pull Request
Howdy there, the issues were the following:

- Curators weren't able to upload books without moving the library computer, because the book scanner was out of range of the library computer.

image
I moved the scanner and the book binder to the same area, so curators won't have to move the computer to upload books.
image

- I saw one space tile that was wrongfully labeled as nearstation, so I fixed that too.
image

- The sec equipment room was missing a distro pipe. Now fixed.
image

## Why It's Good For The Game
Curators can upload books and ordnance has the full equipment!
And I guess sec will get air in the equipment room if it's lacking...

## Changelog

:cl:
fix: Moved the library book binder and scanner to the same area as the library computer.
fix: The security equipment room's air pump is now connected to distro.
/:cl:

### CODE REVIEW

**Comment by OperativeLyn** [comment]
> Would you mind fixing this too in the meantime? Just a pipe. image

You got it chief.

**Comment by OperativeLyn** [comment]
> This isn't how tank compressors work...

Care to explain instead of giving a vague response?

**Comment by SmoSmoSmoSmok** [comment]
> > Would you mind fixing this too in the meantime? Just a pipe. image
> 
> You got it chief.

? Y r u undoing my hardwork. thsi was an intended feature designed to sufocate police (i did this on purpos)

**Comment by OneAsianTortoise** [comment]
> > > Would you mind fixing this too in the meantime? Just a pipe. image
> > 
> > 
> > You got it chief.
> 
> ? Y r u undoing my hardwork. thsi was an intended feature designed to sufocate police (i did this on purpos)

^doesn't know pubby brig n2o distro

**Comment by Pepsilawn** [comment]
> > This isn't how tank compressors work...
> 
> Care to explain instead of giving a vague response? Edit: Ok yeah you need to have a connector and a filter attached to it. Next time tell me instead of doing that, I hate it.

Ebb included the tank compressor in his month-old toxins pr after tgu was merged so I wasn't sure if you were going to keep it in yours

**Comment by OperativeLyn** [comment]
Alright yea I'll remove the tank compressor from mine if he's doing it

**Pull request merged**
