### PR TITLE
SeleneStation: Small botany renovation 

### PR DESCRIPTION
**Pull request by EIB0N**
## About The Pull Request

Moved some of the machines in botany around so it is less clustered

## Why It's Good For The Game

complaint was made about botany getting clustered with the current layout although this one is fairly simple I hope it fixes the issue without having to change it completely 

download (1)

## Changelog
:cl:

balance: Moved machines in botany around a bit to help with cluttering 

/:cl:

### CODE REVIEW

**Comment by Helianthus00** [comment]
Why did you remove the two trays in the top right?

**Comment by EIB0N** [comment]
> Why did you remove the two trays in the top right?

there are enough trays in my opinion also having the trays there create a choke point

**Comment by Helianthus00** [comment]
I'd prefer if the number of trays wasn't decreased

**Comment by EIB0N** [comment]
> I'd prefer if the number of trays wasn't decreased

is lowering the number of tables ok?

**Comment by Helianthus00** [comment]
Sure, but keeping the trays in groups of 2/3 was intentional to prevent cross-pollination without using windoors.

**Comment by remove32** [comment]
*thumps table with fists* 

WHERES MY GODDAMN TRAYS

**Comment by EIB0N** [comment]
> Sure, but keeping the trays in groups of 2/3 was intentional to prevent cross-pollination without using windoors

Hm ok I'll try it out then that makes things much easier

**Pull request merged**
