### PR TITLE
Adds Theia Station Emergency Shuttle (and retroactively fixes braziers which apparently broke with the last TGU)

### PR DESCRIPTION
**Pull request by QuiteLiterallyAnything**
## About The Pull Request
This PR adds a new emergency shuttle to serve as the default shuttle for Theia Station.

image
## Why It's Good For The Game
Theia Station currently lacks its own emergency shuttle whereas every other map in rotation doesn't. 
## Changelog
:cl:
add: Added Theia Station Emergency Shuttle
/:cl:

### CODE REVIEW

**Comment by SgtHunk** [comment]
merge conflicf

**Comment by QuiteLiterallyAnything** [comment]
> merge conflicf

Fixed 😎

**Comment by Pepsilawn** [comment]
Merge conflict (lol)

**Comment by QuiteLiterallyAnything** [comment]
> Merge conflict (lol)

F̷i̷x̶e̷d 😎

**Pull request merged**
