### PR TITLE
Body cameras 2.0

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Security can now purchase 6 body camera upgrades at the SecTech vendor, allowing you to connect bodycameras to a jumpsuit using your ID. This gets deactivated if you re-use your ID on the jumpsuit, get EMP'ed, or get the suit stripped off your person.

## Why It's Good For The Game

Holy shit pleasep lease please ple s

## Changelog
:cl:
add: Body camera upgrades at your local SecTech vendor
/:cl:

### CODE REVIEW

**Comment by remove32** [comment]
just wanna note here since someone mentioned using this in court:
the video feed is NOT recorded anywhere. this is the same thing as having a camera on the wall. 
The most use this will have is in monitoring who is where and what they're doing as a snapshot. 
Especially useful in case a sec member dies in maints...

**Comment by ModDownloading** [comment]
Helps Warden and maybe AI actually keep track of the security team, nifty!

**Comment by Fikou** [comment]
this seems like detective's spy glasses with jumpsuit-attachable cameras but less interesting

**Comment by JohnFulpWillard** [comment]
> this seems like detective's spy glasses with jumpsuit-attachable cameras but less interesting

Only one person can view that, and it’s a 3x3 camera rather than an actual camera, and can only be used on sec suits

**Pull request merged**
