### PR TITLE
[IDB IGNORE] Removes Bloodsuckers

### PR DESCRIPTION
**Pull request by SgtHunk**
## Changelog

:cl:
del: Removed Bloodsuckers from the game.
/:cl:

## About The Pull Request

Removes the Bloodsucker antagonist.
This antag is not fun for anyone. It just becomes a repetitive chore of waiting to level up, and then slowly becoming more of a mary sue with your only weakness being 'burn damage' (you have multiple methods of reducing that whether it be from melee, lasers, or fire).
Or in the case of the person who is on the receiving end of a bloodsucker, instantly dying after getting sucked dry by a bloodsucker who rushed predatory lunge and you failing the grab resist, with the only consequence being loss of 'humanity' (system which is stupid because it depends on the existence of more bloodsuckers and an increase in frenzy is an advantage in certain cases).
Not to mention the increased amount of bugs that this antagonist brings, to the point of breaking entire rounds.
I have never had any fun with this antagonist, and to think that someone like John Willard has made them makes me dislike them even more.
Removing them is for the best in the long term, while we wait for TheSwain to come back and rework them in a way to makes them properly work.

## Why It's Good For The Game

lol sike it just organizes the fulp folder a bit better
Adds an 'antagonist' folder that holds all antag-related stuff (bloodsucker, antag_tips & ert)
moves moth customization to the species folder
idk if im missing something but it'd be good to testmerge in case something breaks

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
we add a github bot and you instantly open false advertising PRs

**Comment by SgtHunk** [comment]
Yeah it'll be dissapointing when people see it's not actually removing bloodsuckers

**Comment by HugoOdaX** [comment]
trolling non-contributors 👍

**Comment by remove32** [comment]
do our changelog comments even make it into the changelog ingame? if so, please change or remove that from this pr so we arent putting abject lies in the changelog

**Comment by SgtHunk** [comment]
they don't
only tg changes do because the github bot makes a changelog file for it

**Comment by remove32** [comment]
cool.

**Comment by Helianthus00** [comment]
hey your pr conflicted because you gave it a dumb name please fix it

**Pull request merged**
