### PR TITLE
TGUI tutorial documentation update

### PR DESCRIPTION
**Pull request by remove32**
## About The Pull Request
I was unsatisfied with the existing documentation, so I updated it with some information that I came up with while learning the framework myself.

## Why It's Good For The Game
Clarified documentation helps new developers get onboarded with the UI framework.

## Changelog
:cl:
spellcheck: Updated TGUI onboarding documentation
/:cl:

### CODE REVIEW

**Comment by remove32** [comment]
oh dear such embarrassing commit history. thank god for squash merged

**Comment by remove32** [comment]
AUGH SHIT THIS IS THE WRONG THING 

DAMMIT

**Comment by JohnFulpWillard** [comment]
Pull Request #200 ruined!

**Comment by remove32** [comment]
shut upshut upshut upshut upshut upshut upshut up

**Comment by JohnFulpWillard** [comment]
why cant i react :trollface:

**Pull request closed without merging**
