### PR TITLE
Makes blast doors/shutters and blast door controllers buildable and deconstructible

### PR DESCRIPTION
**Pull request by HugoOdaX**
## About The Pull Request
As the title says, I made blast doors/shutters buildable through the crafting menu (they aren't cheap to build) and blast door controllers through autolathes. As well as making them linkable and deconstructible with a few steps.

**To build the shutters**: 15 plasteel, 5 cable coil and airlock electronics (crafting menu)
**To build blast doors**: 30 plasteel, 15 cable coil and airlock electronics (crafting menu)
**To make blast door controllers**: 100 iron and 50 glass (autolathe)
**To link blast doors and blast doors controllers**: Use a multitool on the controller and choose an ID, then use a multitool on the blast door and input the same ID as the controller, put the controller in a button and voilá, it's ready to open and close.
**To deconstruct blast doors/shutters**: First you have to open the maintenance panel with a screwdriver, then crowbar the electronics out, cut the cables with a wirecutter and finally tear it down with a welder. Each step takes some time so it isn't as easy to deconstruct.

## Why It's Good For The Game
I love building stuff in ss13 and I think this is a great addition to everyone who likes building as I do.

## Changelog
:cl:
add: Added blast doors and shutters to the crafting menu and blast door controllers to autolathes. As well as deconstruction steps.
/:cl:

### CODE REVIEW

**Comment by remove32** [comment]
Is this not a thing in TG? 
If not, they would be very interested in this PR and I would recommend you check there. They are going through things like crematoriums which previously were not constructable and are fixing these oversights.

**Comment by HugoOdaX** [comment]
> Is this not a thing in TG? 
> If not, they would be very interested in this PR and I would recommend you check there. They are going through things like crematoriums which previously were not constructable and are fixing these oversights.

Yeah I think im gonna do it there, should I close this?

**Comment by GoldenAlpharex** [comment]
However, a conscern I have with having some deconstruction steps for these is, people could now deconstruct them, which means that they lose that whole "impenetrable unless you break it" kind of feel, meaning that it's much easier to break into an area that's protected by those than it was in the past.

**Comment by HugoOdaX** [comment]
> However, a conscern I have with having some deconstruction steps for these is, people could now deconstruct them, which means that they lose that whole "impenetrable unless you break it" kind of feel, meaning that it's much easier to break into an area that's protected by those than it was in the past.

I made it so you can only deconstruct em if they are open, so you cant cheese a closed one by deconstructing it

**Comment by remove32** [comment]
> 
> 
> > Is this not a thing in TG?
> > If not, they would be very interested in this PR and I would recommend you check there. They are going through things like crematoriums which previously were not constructable and are fixing these oversights.
> 
> Yeah I think im gonna do it there, should I close this?

you can leave it open but for sure check if they have this n TG already and if not try to get it in there

**Comment by HugoOdaX** [comment]
> > 
> > 
> > > Is this not a thing in TG?
> > > If not, they would be very interested in this PR and I would recommend you check there. They are going through things like crematoriums which previously were not constructable and are fixing these oversights.
> > 
> > Yeah I think im gonna do it there, should I close this?
> 
> you can leave it open but for sure check if they have this n TG already and if not try to get it in there

Already did a PR in TG, they didn't have it for sure

**Comment by remove32** [comment]
OK so since TG merged this, I'm gonna close this and just import your changes from upstream. Congrats btw!

**Pull request closed without merging**
