### PR TITLE
Removes old nanite relics from the game

### PR DESCRIPTION
**Pull request by Bilbo367**
## About The Pull Request

Removes fluff, and the appropriate fluff stuff on helio

## Why It's Good For The Game

We have nanites so it don't make sense to have a relic site.

### CODE REVIEW

**Comment by Horatio22** [comment]
Excellent fix. There's going to be a merge conflict with the other helio pr but otherwise I think this is great

**Review by SgtHunk — CHANGES_REQUESTED** [review]
Good, but in this case you have to replace the maint room now with some other fluff theme, since its original design was meant to be a nanite lab

**Comment by Bilbo367** [comment]
How about this?
Screenshot 2024-03-17 100031

**Comment by Bilbo367** [comment]
How about dis?
image

**Review by SgtHunk — APPROVED** [review]

**Pull request merged**
