### PR TITLE
Return of the Banned Beefmen

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

That wasn't a 'meme'.

### CODE REVIEW

**Comment by SpaceDragon00** [comment]
Tom replied to the previous PR with his thoughts on the matter

image

**Comment by JohnFulpWillard** [comment]
> 
> 
> Tom replied to the previous PR with his thoughts on the matter
> 
> image

It was not a 'meme' when I added it, it was a serious thing for a serious PR.
You still haven't explained how it could be powergamed in a way that can actually happen without admins constantly changing your race.

**Comment by Helianthus00** [comment]
My concerns are more within things like IC race changes, which could be used instead to cycle between beefman and human if the player is banned from that race. It is a fun idea but introduces some fringe issues while not really adding much.

**Comment by JohnFulpWillard** [comment]
> 
> 
> My concerns are more within things like IC race changes, which could be used instead to cycle between beefman and human if the player is banned from that race. It is a fun idea but introduces some fringe issues while not really adding much.

What difference would it be from using mutation toxin at that point? This is harder to do anyways because human mutation toxin is 100% while uh... I guess Lizard mutation toxin? (Felinid/Ethereal mutation toxin isnt a thing outside of the randomized race extract), is only 50% chance.

**Comment by Helianthus00** [comment]
Seems unnecessary to me and would just cause more confusion for players. I'd rather things stay consistent when it comes to bans and such, especially so that the felinid ban can be treated seriously and not as a joke for players.

**Pull request closed without merging**
