### PR TITLE
Removes wings.

### PR DESCRIPTION
**Pull request by StoneMason**
## About The Pull Request

Removes the wings introduced in: https://github.com/fulpstation/fulpstation/pull/43

## Why It's Good For The Game

They're stupid i hat ethem we should remove them they're bloats for psirtes 
who eevne pr ed the shit 

in reality they're tg now https://github.com/tgstation/tgstation/pull/64293

## Changelog

:cl:

del: Removed moth wings

/:cl:

### CODE REVIEW

**Comment by SgtHunk** [comment]
idc

**Comment by StoneMason** [comment]
speedmerge this there's this one moth player which uses these wings all the time itd be rewally funny to annoy him and make him unable to use the wings until the next tgu

**Comment by OneAsianTortoise** [comment]
> speedmerge this there's this one moth player which uses these wings all the time itd be rewally funny to annoy him and make him unable to use the wings until the next tgu

cry about it

**Comment by Helianthus00** [comment]
I hate moths

**Pull request merged**
