### PR TITLE
Selene Medbay QOL

### PR DESCRIPTION
**Pull request by Cass-Bitchcoin**
## About The Pull Request

This renovates Selene Station's medbay a bit to hopefully remedy some issues I've noticed.
- A disposal bin was added to medbay central.
- Surgery rooms have been fitted with defibrillator mounts and the glass tables have been reinforced.
- The exam room now has tables with a straight jacket, earmuffs, blindfold, and various other items.
- Stamps have been added to CMO's office.
- The chemistry lab has been slightly expanded. There is now an airlock leading directly into maintenance, the disposal bin has been moved a bit more out of the way, and the scrubber pipes coming from the smoke room have been moved to the correct layer.
- Virology has been with fitted breach prevention doors. Virologists will also be provided with handcuffs for their test subjects as most stations do.

## Changlelog
🆑
qol: disposal bin to central
qol: defibrillator mount in surgery
balance: reinforced glass tables in surgery
add: straight jacket, earmuffs, blindfold, pajamas to exam room
fix: stamp to cmo office
fix: smoke room scrubber pipes on 2nd layer instead of 3rd
balance: chemlab beeger
qol: chemlab maintenance access
balance: virology blast doors
qol: virology has handcuffs now
fix: I moved an action figure to the exam room C:
balance: blood filter removed from central and added to surgery
fix: a camera in virology was floating off a wall
/🆑

### CODE REVIEW

**Comment by Cass-Bitchcoin** [comment]
I believe the merge conflict was from a lattice I left stacked on a wall by mistake. It should be removed now.

**Comment by Pepsilawn** [comment]
Its from TGU

**Comment by Pepsilawn** [comment]
Easiest is to replicate your changes into master, or replicating TGU changes onto your branch
Otherwise solving mapping conflicts is a bit of a coin toss IMO

**Comment by Cass-Bitchcoin** [comment]
MapDiffBot2 has been on waiting for over a week. Is there something I need to do to have it run or should I just be submitting this a second time?

**Comment by SgtHunk** [comment]
> MapDiffBot2 has been on waiting for over a week. Is there something I need to do to have it run or should I just be submitting this a second time?

MDB2 is broken, not your fault
you still have conflicts though

**Pull request closed without merging**
