### PR TITLE
Brigdoc tweaks + clean-up

### PR DESCRIPTION
**Pull request by SgtHunk**
Tweaks Brig Physician after feedback from live-testing.

## Tweaks

- Instead of a baton, they spawn with a flash on their pocket, to only serve as self-defense. Due to this, they no longer have a weapons permit.
- They now spawn with Security Office access on highpop (only lowpop previously), to prevent them being stuck on security office.
- They now no longer have a medical belt with surgery tools, instead they have a compact defib. To make up for this, their first aid kit is now the same MDs get (with basic tend wounds surgery tools), and they're free to go roundstart to medbay to get their 2 other tools.
- They have a special medkit with contents similar to the one MD's get. One of the most distinct tools in there is a Crew Monitor, as I felt that them not knowing how their officers currently are regarding health was... counter-productive. (And well, the only crew monitoring console in the brig is in the Warden's office)

## Additions

- Beefmen brigdocs now have a sash.
- You can order crates with brigdoc clothing at cargo (This is to make up for the fact you can't get the clothing anywhere else).

image

## Why It's Good For The Game

Discourages brigdoc to validhunt, enforces it, and also allows them to roam brig without struggling due to not being able to leave sec office.

## Changelog
:cl:
add: Added brig physician clothing kits, to buy at cargo.
tweak: Tweaked brig physician's roundstart equipment, they no longer have batons, but only a flash as a self defense tool. They also now have a compact defib to make up for the lack of a revival method. They have their own special medkit now.
/:cl:

### CODE REVIEW

**Comment by Kalesonki** [comment]
Your crate contains regular MedHUD, yet brigdoc spawns with MedHUD sunglasses. Is this intended?

Regarding compact defib - it can be easily emped and Brig Phys has access, as well as has to go to medical roundstart for boards for operating computers, otherwise - just print batons from sec lathe, given they will  have access. Otherwise, compact defib was something unique about CMO, locked behing tech for others to get. Brig Doc getting compact defibs, while Paras don't get them is kinda meh imho.

**Comment by JohnFulpWillard** [comment]
> it can be easily emped and Brig Phys has access
not early in the round

> while Paras don't get them is kinda meh imho.
why would paramedics need a defib? if we were able to edit maps, we would just add a defib to brig medical area, but we cant, so a compact defib roundstart sounds like a good compromise.

**Comment by SgtHunk** [comment]
> Your crate contains regular MedHUD, yet brigdoc spawns with MedHUD sunglasses. Is this intended?

Yes. I'd rather if the amount of sunglasses on station was limited. If you want to make yourself MedHUD Sunglasses, deconstruct SecHUDs.

> Regarding compact defib - it can be easily emped

So can CMO's, but that's powergaming.

Before, the stun baton was meant to be used for revival. However, after feedback, people mistook the role as 'doctor that can validhunt'. By removing the baton and weapons access, the most self defense is a flash. So giving them a compact defib was only logical.

> Just print batons from sec lathe

That was a fulp-only change which we don't have.

> Brig Doc getting compact defibs, while Paras don't get them is kinda meh imho.

Brig Doc is meant to stay in the brig, occasionally going out for supplies, tool upgrades, implants, etc. Paramedics are not meant to revive people. Paramedics constantly go out, stabilize bodies, and bring them to their static counterpart that stays in Medical: the Medical Doctor. They only have to revive others in emergencies.

> Otherwise, compact defib was something unique about CMO, locked behing tech for others to get.

Trust me, if I could, I'd add defibs to Brig Infirmaries. But we can't edit TG maps, so this will do.

**Comment by Kalesonki** [comment]
But would it be possible to make  them start with regular defib in hand? Maybe that would be a good compromise?

**Comment by SgtHunk** [comment]
> But would it be possible to make them start with regular defib in hand? Maybe that would be a good compromise?

That sounds a bit... odd of a middle-ground.
It's a bulky item and having to go through the hassle of putting it on your back slot to replace your backpack temporarily is a bit impractical.
But if more people want that change, I can do it.

**Comment by SoreYew** [comment]
> 
> 
> > But would it be possible to make them start with regular defib in hand? Maybe that would be a good compromise?
> 
> That sounds a bit... odd of a middle-ground.
> It's a bulky item and having to go through the hassle of putting it on your back slot to replace your backpack temporarily is a bit impractical.
> But if more people want that change, I can do it.

I think the intention would be to print a mount and apply it to the spot of their choice. 
Also, Brig Doc starts with a bottle of formaldehyde, but no syringe. Their counterpart paramedic, which also has that item at spawn, does have a syringe.  Having some hours on the job, it is kind of silly I have to steal one from the security post, which has bottles intended to use with it, or trek all the way to medical and buy one/take one.

**Comment by Helianthus00** [comment]
I'm not a fan of more compact defibs being around at roundstart. It's supposed to be a later-round item and there is only one CMO. I'd prefer that to be removed in favor of some other solution.

**Comment by SgtHunk** [comment]
talked with willard about this and settled with a beacon to give them their necessary equipment, going to work on it soon

**Comment by SgtHunk** [comment]
New branch soon tm

**Pull request closed without merging**
