### PR TITLE
Some Selene fixes

### PR DESCRIPTION
**Pull request by Pepsilawn**
image
image

 viro's disposal was never connected to anything & this is my fix

image
image
image

 some shit out in space not having areas/nearstation

image

idk what this is about & if its intended or not id like to know what the reason behind this is & if it needs fixing or not

also replaced most space injectors with passive vents cuz theyre awesomer

image
some asshole built this & it somehow got merged i want to fix it but ig ill wait for tgu first before including it since its on a lot of maps unless john wants to do because the perma as well as the tumor sticking out of it are his

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
expansion: Expands content of an existing feature
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by OperativeLyn** [comment]
You should fix your changelog... NOW!

**Comment by Pepsilawn** [comment]
not rly tbh

**Comment by Helianthus00** [comment]
> idk what this is about & if its intended or not id like to know what the reason behind this is & if it needs fixing or not

No that isn't intended

**Comment by Pepsilawn** [comment]
today i will use the web editor to resolve mapping conflcits

**Pull request merged**
