### PR TITLE
Heliostation

### PR DESCRIPTION
**Pull request by Helianthus00**
## About The Pull Request
Ports Heliostation to the new repo. 

## Why It's Good For The Game
#1 

## Changelog
:cl:
add: Adds Heliostation
/:cl:

### CODE REVIEW

**Comment by Helianthus00** [comment]
Well, no idea why that failed

**Comment by remove32** [comment]
looks like a bunch of divide by zeros in the integration test. would be an upstream issue

**Comment by remove32** [comment]
@SgtHunk any clues why the Integration Tests are still failing? I ran it again after merging your PR that was supposed to fix it.

**Comment by SgtHunk** [comment]
No real idea, my best bet would be that they need to fetch upstream so that their branch is up-to-date with the fix

**Comment by remove32** [comment]
> 
> 
> No real idea, my best bet would be that they need to fetch upstream so that their branch is up-to-date with the fix

shit you probably right. i forgot that the CI stuff only runs against the importing code, even if the merged repo wouldn't fail

**Comment by Helianthus00** [comment]
Well, I didn't rebase, but monkies fixed it somehow. Works for me.

**Comment by remove32** [comment]
good enough for a first past

**Pull request merged**
