### PR TITLE
Fixes bruhspace grammar

### PR DESCRIPTION
**Pull request by zzzmike**
## About The Pull Request

I love the old bruhspace anomaly event which is why I want the warning to make more sense. The bruh moment itself is not issued, the warning for it is. Thanks for coming to my ted talk.

## Why It's Good For The Game

My immersion.

## Changelog

:cl:
fix: bruhspace event grammar
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
i issued it

**Comment by JohnFulpWillard** [comment]
it was a bruh moment so nanotrasen issued it

**Comment by JohnFulpWillard** [comment]
nanotrasen issued the bruh moment

**Comment by JohnFulpWillard** [comment]
there was a bruh moment required

**Comment by zzzmike** [comment]
it's an anomaly, they don't issue anomalies, they issue warnings about them

**Comment by Pepsilawn** [comment]
bruh

**Pull request merged**
