### PR TITLE
Heliostation minor changes and additions

### PR DESCRIPTION
**Pull request by Sadboysuss**
## About The Pull Request
Minor changes that improve the map and additions of new stuff

## Why It's Good For The Game

moar stuff = good
## Changelog
:cl:
add: surgical tape, bone gel and bone setters to operating rooms in medbay.
add: renamed the tesla/singulo area to the west of the station to "Auxiliary Engine Construction" and expanded the area for singulo/tesla enthusiasts. Connected to the power net and "Atmos to engine" pipenet. 
image
add: added full arcmining refinery to mining office 
image
del: removed bonesetter that spawns in medbay treatment area.
fix: replaced bridge walls with R-walls
qol: moved engi cell charger closer to the fab, this makes it easier to find and closer to where it is needed. 
fix: fixed atmos burn chamber filter output outputting to waste instead of to the can 
image
image

/:cl:

### CODE REVIEW

**Comment by Sadboysuss** [comment]
image
so I had to change it to this...

**Comment by Sadboysuss** [comment]
also closes these: https://github.com/fulpstation/fulpstation/issues/1127  https://github.com/fulpstation/fulpstation/issues/1137

**Comment by Sadboysuss** [comment]
I forgor the lever for the refiner smh

**Comment by Horatio22** [comment]
> ## Why It's Good For The Game
> 
> moar stuff = good

This is an absolutely terrible approach to map design.

> ## Changelog
> 
>. add: renamed the tesla/singulo area to the west of the station to "Auxiliary Engine Construction" and expanded the area for singulo/tesla enthusiasts. 

Engineering having a... satellite? area without any cameras makes no sense, and you're better off removing the whole thing than leaving it like this.
>add: added full arcmining refinery to mining office image

This is better than no forge, but it still isn't good, and completely ignores my previous feedback about it being difficult to operate with boxes (especially if there's more than 1 miner wanting to use it). I'd encourage you to redesign the space so that you aren't restricted to a 1 tile wide hall to use it.

**Comment by Sadboysuss** [comment]
>Engineering having a... satellite? area without any cameras makes no sense, and you're better off removing the whole thing than leaving it like this. To be clear, I'm not saying to simply add cameras here. Unless you can find something worthwhile to put here besides "moar stuff = good", you should delete this area.

As I said before that area is for construction of secondary engines, doing singularity delams, tesla delams, second SM, even nebula shields. This is a great place for engineers to experiment with dangerous mechanics with a lesser threat to the station as a whole, this is a feature of Heliostation and any engineer deciding to experiment wkth an SM setup loves this area , I can put an empty SM chamber here since that would make sense but I'd honestly rather leave it for engineers to make their own stuff here.

>This is better than no forge, but it still isn't good and completely ignores my previous feedback about it being difficult to operate with boxes (especially if there's more than 1 miner wanting to use it). I'd encourage you to redesign the space so that you aren't restricted to a 1 tile wide hall to use it.

It was a 1 tile space before and no one will carry ore boxes here because it automatically transports boulders and processes them, but I see your concern and will adress it.

**Comment by Horatio22** [comment]
> As I said before that area is for construction of secondary engines, doing singularity delams, tesla delams, second SM, even nebula shields. This is a great place for engineers to experiment with dangerous mechanics with a lesser threat to the station as a whole, this is a feature of Heliostation and any engineer deciding to experiment wkth an SM setup loves this area , I can put an empty SM chamber here since that would make sense but I'd honestly rather leave it for engineers to make their own stuff here.

Yeah, an empty space for engineers to test dangerous stuff that doesn't really make sense with the rest of the map is not a reasonable use of space imo. It doesn't add much to the station and just serves to encourage engineers to run off and do pointless solo projects instead of interacting with the rest of the station. If someone wants to do dangerous experiments that badly, they can just pull up dream deamon and run their own test server. I won't merge it with a random floating testing room.

**Comment by Sadboysuss** [comment]
> 
> > As I said before that area is for construction of secondary engines, doing singularity delams, tesla delams, second SM, even nebula shields. This is a great place for engineers to experiment with dangerous mechanics with a lesser threat to the station as a whole, this is a feature of Heliostation and any engineer deciding to experiment wkth an SM setup loves this area , I can put an empty SM chamber here since that would make sense but I'd honestly rather leave it for engineers to make their own stuff here.
> 
> Yeah, an empty space for engineers to test dangerous stuff that doesn't really make sense with the rest of the map is not a reasonable use of space imo. It doesn't add much to the station and just serves to encourage engineers to run off and do pointless solo projects instead of interacting with the rest of the station. If someone wants to do dangerous experiments that badly, they can just pull up dream deamon and run their own test server. I won't merge it with a random floating testing room.

Ok I'll remove it but a lot of the engi players won't like it including me

**Comment by Sadboysuss** [comment]
changed the mining to this:
Before- 
image
Now- 
image

Aux engine area is gone - 
image

@Horatio22 pls review

**Comment by Horatio22** [comment]
> > 
> > > As I said before that area is for construction of secondary engines, doing singularity delams, tesla delams, second SM, even nebula shields. This is a great place for engineers to experiment with dangerous mechanics with a lesser threat to the station as a whole, this is a feature of Heliostation and any engineer deciding to experiment wkth an SM setup loves this area , I can put an empty SM chamber here since that would make sense but I'd honestly rather leave it for engineers to make their own stuff here.
> > 
> > Yeah, an empty space for engineers to test dangerous stuff that doesn't really make sense with the rest of the map is not a reasonable use of space imo. It doesn't add much to the station and just serves to encourage engineers to run off and do pointless solo projects instead of interacting with the rest of the station. If someone wants to do dangerous experiments that badly, they can just pull up dream deamon and run their own test server. I won't merge it with a random floating testing room.
> 
> Ok I'll remove it but a lot of the engi players won't like it including me

If you really wanna keep it, @Pepsilawn  suggested making it into an abandoned area (like in Meta) which I think would be a much better alternative than a free, highly reinforced play area. You could also use it to pay homage to what the room was originally used for pike the abandoned cloning rooms in some medbay maints. Regardless, this looks good so I'll add it to the tm.

**Comment by Sadboysuss** [comment]
> > > > As I said before that area is for construction of secondary engines, doing singularity delams, tesla delams, second SM, even nebula shields. This is a great place for engineers to experiment with dangerous mechanics with a lesser threat to the station as a whole, this is a feature of Heliostation and any engineer deciding to experiment wkth an SM setup loves this area , I can put an empty SM chamber here since that would make sense but I'd honestly rather leave it for engineers to make their own stuff here.
> > > 
> > > 
> > > Yeah, an empty space for engineers to test dangerous stuff that doesn't really make sense with the rest of the map is not a reasonable use of space imo. It doesn't add much to the station and just serves to encourage engineers to run off and do pointless solo projects instead of interacting with the rest of the station. If someone wants to do dangerous experiments that badly, they can just pull up dream deamon and run their own test server. I won't merge it with a random floating testing room.
> > 
> > 
> > Ok I'll remove it but a lot of the engi players won't like it including me
> 
> If you really wanna keep it, @Pepsilawn suggested making it into an abandoned area (like in Meta) which I think would be a much better alternative than a free, highly reinforced play area. You could also use it to pay homage to what the room was originally used for pike the abandoned cloning rooms in some medbay maints. Regardless, this looks good so I'll add it to the tm.

maybe I'll come back to it later but right now I don't want to touch it without a good plan

**Comment by SgtHunk** [comment]
can you plz not do double walls they suck

**Comment by Sadboysuss** [comment]
> can you plz not do double walls they suck 

yeah my bad I'll fix it

**Comment by Sadboysuss** [comment]
fixed double walls 
image

**Comment by Sadboysuss** [comment]
unrelated failed test

**Comment by Horatio22** [comment]
> unrelated failed test

We can see what tests fail - no need to comment every time

**Pull request merged**
