### PR TITLE
Extra pride wings!

### PR DESCRIPTION
**Pull request by Greniza**
## About The Pull Request

Happy pride month! Adds Twilight, Metamorphosis, and Cyberbliss moth wings and antennae.

Twilight:
image

Metamorphosis (blue antennae variant):
image

Metamorphosis (pink antennae variant):
image

Cyberbliss (credit to Beatrice):
image

## Why It's Good For The Game

Adds Twilight, Metamorphosis, and Cyberbliss moth antennae and wings, which are bi-, trans-, and gay- pride wings respectively, meant to be a permanent version of #241.

## Changelog
:cl:
imageadd: More moth cosmetics, Twilight, Metamorphosis, and Cyberbliss. Credit to Beatrice for the base Cyberbliss sprite.
/:cl:

### CODE REVIEW

**Comment by Nobelium-XVIII** [comment]
Now make the respective antennae and marking

**Comment by Greniza** [comment]
> Now make the respective antennae and marking

ok

**Comment by NullFag** [comment]
The fact I have to download the entire codebase just to port this properly pains me mildly.

**Comment by Greniza** [comment]
> The fact I have to download the entire codebase just to port this properly pains me mildly.

I could send you stuff in a bit, so you don’t have to bother with downloading it. Besides, the PR doesn’t have markings corresponding with the wings, so it really wasn’t meant to be put much of anywhere else.

**Comment by SgtHunk** [comment]
> The fact I have to download the entire codebase just to port this properly pains me mildly.

bro you can literally download the files from the PR

**Comment by NullFag** [comment]
> I could send you stuff in a bit, so you don’t have to bother with downloading it. Besides, the PR doesn’t have markings corresponding with the wings, so it really wasn’t meant to be put much of anywhere else. Where are you planning on porting it to?

At the time I was porting it to bobstation, now I'm porting it to Tempt.

**Pull request merged**
