### PR TITLE
Pubby additions and fixes

### PR DESCRIPTION
**Pull request by Sadboysuss**
## About The Pull Request

fixes some stuff and adds some stuff
## Why It's Good For The Game

stuff is good, everything is in the changelog
## Changelog
:cl:
add: cell charger to engineering 
image

add: foundry in pubby: 
Before - 
image

Now - 
image
balance: AI sat disabler turrets will actually do something 
Before - 
image
Now - 
image
/:cl:

### CODE REVIEW

**Comment by Sadboysuss** [comment]
Closes this https://github.com/fulpstation/fulpstation/issues/1140

**Comment by Pepsilawn** [comment]
The cargo change makes it way easier to fall in and potentially softlock yourself

**Comment by Sadboysuss** [comment]
@Pepsilawn the airtight flaps only let through lying down people no?

**Comment by Pepsilawn** [comment]
> @Pepsilawn the airtight flaps only let through lying down people no?

no

**Comment by Sadboysuss** [comment]
> > @Pepsilawn the airtight flaps only let through lying down people no?
> 
> no

I could put a windoor down then, would that solve it?

**Comment by Pepsilawn** [comment]
> I could put a windoor down then, would that solve it?
Would make loading the shuttle tedious better to find another smelter design

**Comment by Sadboysuss** [comment]
> > I could put a windoor down then, would that solve it?
> 
> Would make loading the shuttle tedious better to find another smelter design

ok I got an idea but I'll do it tomorrow

**Comment by Sadboysuss** [comment]
image

how about now

**Comment by Horatio22** [comment]
> image
> 
> how about now

I agree that cargo needs to be updated, but this looks like a mess of conveyor belts with no real purpose.

**Comment by Sadboysuss** [comment]
> > image
> > how about now
> 
> I agree that cargo needs to be updated, but this looks like a mess of conveyor belts with no real purpose. I'd like to see this reworked with either the middle conveyor belt redone or removed before I will merge it.

Ok I'll see what I can do

**Comment by Sadboysuss** [comment]
> > image
> > how about now
> 
> I agree that cargo needs to be updated, but this looks like a mess of conveyor belts with no real purpose. I'd like to see this reworked with either the middle conveyor belt redone or removed before I will merge it.

https://github.com/fulpstation/fulpstation/pull/1147#issuecomment-1989768181

Is this good or should I make it symmetrical with the conveyor belt below?

**Comment by Sadboysuss** [comment]
image

**Comment by Sadboysuss** [comment]
image
now looks like this

**Comment by Sadboysuss** [comment]
image
how it looks currently

image
moved the drone dispenser because it is indestructible and blocks access to the server area, secondary objectives require you to destroy the research server and this gives a fair option to break in from topside

**Comment by Sadboysuss** [comment]
@Horatio22 please review

**Comment by Horatio22** [comment]
> @Horatio22 please review

Pepsi says the shutter buttons still don't work. This needs to be fixed before this can be merged.

**Comment by Sadboysuss** [comment]
> > @Horatio22 please review
> 
> Pepsi says the shutter buttons still don't work. This needs to be fixed before this can be merged.

https://imgur.com/a/p0bTjB3

It works I just tested it

**Comment by Horatio22** [comment]
> @Horatio22 please review

    Looks good!

**Pull request merged**
