### PR TITLE
[MDB IGNORE] [IDB IGNORE] October TGU

### PR DESCRIPTION
**Pull request by Pepsilawn**
tumblr_morqfbJ8WO1swgfzvo1_400

### CODE REVIEW

**Comment by OneAsianTortoise** [comment]
oh boy time to make a mapping PR rn

**Comment by AffectedArc07** [comment]
`[MDB IGNORE] [IDB IGNORE]` in the title please for the love of god.

**Comment by Pepsilawn** [comment]
> `[MDB IGNORE] [IDB IGNORE]` in the title please for the love of god.

Headmin lied and told me MDB2 was strong enough...

**Comment by AffectedArc07** [comment]
> > `[MDB IGNORE] [IDB IGNORE]` in the title please for the love of god.
> 
> Headmin lied and told me MDB2 was strong enough...

MDB2 is. You still have IDB1 running though.
image

**Comment by Pepsilawn** [comment]
> MDB2 is. You still have IDB1 running though. image

Uh, it's meant to be suspended I guess I'll bring it up, thanks.

**Comment by Pepsilawn** [comment]
@AffectedArc07 Wind just set up IDB2, IDB1 is suspended forever so we shouldn't be blowing up your console anytime soon. Thanks!

**Comment by SgtHunk** [comment]
whas up with screenshot tests

**Pull request merged**
