### PR TITLE
Updates Selenestation with directionals

### PR DESCRIPTION
**Pull request by SgtHunk**
## About The Pull Request

title
Keeping on draft until I finish checking everything went well and I replaced all of the strays
yes this uses a script deal with it

NOTE: This used a script for 90% of the work. There's a very small chance that some directionals did not get correctly set. Please report these upon addition of this pull request.

### CODE REVIEW

**Review by JohnFulpWillard — APPROVED** [review]
Delete the map.

**Comment by SgtHunk** [comment]
shhh this is a scheme to give eibon mapping conflicts

**Comment by Helianthus00** [comment]
The perma thing is gonna conflict but that should be a really easy fix

**Pull request merged**
