### PR TITLE
Updates the Fulpstation codebase to the 01/08/2022 version of the tgstation repository

### PR DESCRIPTION
**Pull request by Pepsilawn**
## About The Pull Request

Also restores our readme that we lost at some point? it went months unnoticed idk how that happened

## Why It's Good For The Game

FUCK YOU STORAGE REFACORT & revenant

## Changelog

:cl:
balance: tgu
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
( removes fulp gags)

**Comment by Pepsilawn** [comment]
since when do we have that

**Comment by JohnFulpWillard** [comment]
since halloween 2021

**Comment by Pepsilawn** [comment]
I think you're hallucinating do you mean like the json settings for them

**Comment by Pepsilawn** [comment]
Nvm I get it now that's kind of annoying

**Comment by Pepsilawn** [comment]
This is literally all Ebb's fault if he hadn't misplaced his stupid sticky tape

**Comment by JohnFulpWillard** [comment]
make sure to mention revenant nerf

**Comment by Pepsilawn** [comment]
thx

**Comment by OneAsianTortoise** [comment]
is pun pun drip included

**Comment by Pepsilawn** [comment]
find out ingame

**Pull request merged**
