### PR TITLE
Add 3 CMO medals and add medal lockbox in locker

### PR DESCRIPTION
**Pull request by RaidenKoizuma**
## About The Pull Request
Added three new medals and a lockbox containing the medals in the CMO's locker. This is my first PR and dive into the code, so if I screwed anything up lemme know. Also, the CMO cape-looking sprite was done by AtlasRules for old repo.
unknown

## Why It's Good For The Game
Every other head has department-specific medals that they are able to give out (aside from engineering, kinda) so its only fair for the CMO. Having medals to give out will give the CMO more opportunity to encourage med staff to do their job well, especially chemists. 

## Changelog
:cl:
add: added three medbay-specific medals and a lockbox to the CMO's locker
/:cl:

### CODE REVIEW

**Comment by StoneMason** [comment]
In future use branches instead of doing it from master.

**Comment by JohnFulpWillard** [comment]
Are you sure the first one is a medal and not the worn sprite icon?

**Comment by RaidenKoizuma** [comment]
I updated the sprites and gave them worn sprites as well. Tested and it functions and appears on the sprites just fine. Do I need to do anything else on my side, or do you guys just review it and such now?

**Comment by SoreYew** [comment]
Medical power creep (good)

**Comment by Helianthus00** [comment]
This is really something that should go upstream. I suggest PRing it to /tg/, and if it is rejected there, we can talk about adding it here.

**Comment by RaidenKoizuma** [comment]
I was told its unlikely to be merged in TG and to just send it here, but I guess I’ll try.

**Comment by SpaceDragon00** [comment]
If you update the sprites make sure to update the screenshots in your PR body aswell. If you have images in the PR some people might not check icon diff bot since they assume you already showed them the sprites

**Comment by RaidenKoizuma** [comment]
Right now it's going through TG, meant to close this til the verdict on TG.

**Pull request closed without merging**
