### PR TITLE
Removes deputies

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Alternative PR to #285

TG's accesses are fucked and people will abuse it basically no matter what you try to do. Unless rules on what deputies are allowed to take actually get enforced, deputies will not fit here.

### CODE REVIEW

**Comment by Helianthus00** [comment]
I'd really prefer to not remove deputies, unless you can no longer find ways around tg's changing of things.

**Comment by SpaceDragon00** [comment]
Im confused about what problem you are specifically having with deputies. I'd like it if you could lay out the specific issue(s) in detail so alternatives can be discussed

**Comment by JohnFulpWillard** [comment]
> 
> 
> Im confused about what problem you are specifically having with deputies. I'd like it if you could lay out the specific issue(s) in detail so alternatives can be discussed

People go to brig, take sec radio and sec gear, then patrol the halls.

**Comment by Helianthus00** [comment]
Merged #285 so I'm closing this

**Comment by ReinaCoder** [comment]
please merge

**Pull request closed without merging**
