### PR TITLE
kid named 'allow player interpretation' (beefman lore update).

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Splits beefmen's lore into paragraphs. I've also taken this time to update it as well, since the old one was made in a rush.
The lore is more focused on the Cook and how the first Beefman was made, allowing everything after that to be up to player interpretation.
image

Also, adds Gibbers to the Beefman stations, as I thought it would be fitting with this current version of lore.

## Why It's Good For The Game

Closes https://github.com/fulpstation/fulpstation/issues/681
Alternative to https://github.com/fulpstation/fulpstation/pull/703

Better than the current version, allows more player interpretation of what the lore is, without driving off course of what it was meant to be
image
image

### CODE REVIEW

**Comment by Pepsilawn** [comment]
Spite PR

**Comment by Pepsilawn** [comment]
Why is the title allow player interpretation when your lore is stated as factual happenings vs me based on IC reports and investigations

**Comment by JohnFulpWillard** [comment]
> Who's the CHef

reed fiddler

**Comment by Pepsilawn** [comment]
whats the russian sol government russia is owned by the spinward coalition

**Comment by JohnFulpWillard** [comment]
> whats the russian sol government russia is owned by the spinward coalition

kid named 'idrc just say its from a long time ago or smth':

**Comment by Pepsilawn** [comment]
Before the spinward coalition was the third soviet union and before that was todays russia :/

**Comment by Sheits** [comment]
as thye 1 who wrote the fly lore i have 2 say this pr sux...

**Comment by SgtHunk** [comment]
Chef named Fiddler:

**Comment by SmoSmoSmoSmok** [comment]
this lore reads like it was made by a 17 year old (it was)

**Comment by Pepsilawn** [comment]
Beefman wasn't originally designed for VR Chat which that picture was made for...

**Pull request merged**
