### PR TITLE
Removes Brig Physician

### PR DESCRIPTION
**Pull request by SgtHunk**
## About The Pull Request

i dont like it

## Why It's Good For The Game

no one will miss this job and it was just used as a baseline for fulp job integration

## Changelog

:cl:
add: hopefully an actually good job next time
/:cl:

### CODE REVIEW

**Comment by ReinaCoder** [comment]
Hey man, the original creator of brig phys said it couldnt be removed another fulp unique job replaced it... so yeah

**Comment by SpaceDragon00** [comment]
Medical deputy (Based) is the replacement for the brig physician (Cringe)

**Comment by Pepsilawn** [comment]
this pr made me realize how ugly the brig doc envirosuit is

**Comment by StoneMason** [comment]
original creator of brig phys' on fulp should kts (keep themself safe)

**Comment by remove32** [comment]
bye bye stinky

**Pull request merged**
