### PR TITLE
June/July TGU: Loadout menu, flatpackers and... whatever else!

### PR DESCRIPTION
**Pull request by FernandoJ8**
## About The Pull Request

What it says on the tin (I still love that phrase). Most of you probably know what's included better than I do, given how long it has been since I played, but I'll list the things that caused issues/were changed in the process of fixing errors:

 - Nanite Research Node prerequisites were altered where the re-structuring of the research tree as a whole demanded it. I've tried to replace the old nodes with ones that are roughly equivalent (mainly based on their unlocks).
 - There's probably going to be a little bit of weirdness with randomizing humans who know russian. Name generation is now tied to language, so the only way for beefmen to retain their "Experiment" and "Meat" styles of names is to tie them to russian. No (good) way to override it, as far as I can tell. Will need upstream modification. For now, it stays as an edge case that is not too impactful.
 - The attack verb for limbs is now a list,  so I added "slaps" as one of the verbs for beefman limbs, both hands and legs. Not strictly necessary, but it seemed amusing. We might as well make use of the change.
 - The fulp world edit required by our species' preference is gone. It's been replaced by a Z-Edit to the Appearance Subsystem found in `Z_edits/fulp_species.dm`
 - Protogens can now choose to have no tail and/or no antennae in their customization.
 - The area of space tiles in our ruins has been changed to NearStation regardless of their placement. I'm not a fan, but it's demanded by one of the Unit Tests. Shouldn't be a big deal, at any rate.
- Added a temporary TG edit in `dna.dm`. It'll be ovewritten in the next TGU when I fix it upstream.

Mapping stuff:
 - Atmos and Toxins have been outfitted with the new pipe scrubbers.
 - Removed security cams from public bathrooms in accordance with https://github.com/tgstation/tgstation/pull/84426.
 - Engineering and Science have been given the new Flatpackers.
 - Turned a bunch of TeleScreens into their directional versions.
 - Replaced items spawns in brigs with the new spawner helpers.
 - Added tinyfans to our shuttles in accordance with https://github.com/tgstation/tgstation/pull/82915.
 - Filled the secure slime chambers in Xenobiology with BZ in accordance with https://github.com/tgstation/tgstation/pull/84452. (In cases where all pens had reinforced floors, I filled only the biggest of the chambers)
 - Ordnance labs have been given APCs for both the burn and freezer chambers. The air alarms of said chambers have also been given the new area helpers in Helio, Selene and Pubby. Theia already had them.

## Changelog
:cl:
add: late june TGU
/:cl:

### CODE REVIEW

**Comment by FernandoJ8** [comment]
Tweaked nanite costs to address #1231. Updated to new TG.

**Comment by SgtHunk** [comment]
merging this as soon as conflicts are resolved

**Comment by FernandoJ8** [comment]
I should document that it's currently up to commit [a8b65dec0c0a11d6335801effda29b079557e4e6 ](https://github.com/tgstation/tgstation/commit/a8b65dec0c0a11d6335801effda29b079557e4e6)from tg.

**Comment by FernandoJ8** [comment]
Updated up to https://github.com/tgstation/tgstation/commit/e40becd742236076f1e29b4cdbbe05d1a5629ab0 as of the latest commit.

Also fixed beefman hair and protogen accesories not matching body colour.

**Pull request merged**
