### PR TITLE
Adds Deputies

### PR DESCRIPTION
**Pull request by Pepsilawn**
## About The Pull Request
This adds a new job to Fulpstation, the deputy, originally created by Mithrandalf.

## Why It's Good For The Game
While security officers have a limited amount of accesses within their assigned departments, deputies are fully equipped to help with any space law related issue wherever they are assigned, and are expected to coordinate with them rather than with the security department. This allows for interesting situations and offers a new unique way of playing the game.

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
I don't want deputies re-added. 👎

**Comment by Pepsilawn** [comment]
You're supposed to say why on my PR

**Comment by JohnFulpWillard** [comment]
is me saying I don't want something i basically made here, not enough

**Comment by Pepsilawn** [comment]
ok

**Comment by SgtHunk** [comment]
why does this have the depsec config pr 🤨

**Comment by Pepsilawn** [comment]
> why does this have the depsec config pr 🤨

Depsec config not being a thing was the reason listed on the removal pr

**Comment by OneAsianTortoise** [comment]
can u not?

**Comment by SmoSmoSmoSmok** [comment]
Give them guns

**Comment by SmoSmoSmoSmok** [comment]
To kill the criminals

**Comment by SmoSmoSmoSmok** [comment]
So they can shoot them with the guns and the guns have real bullets so the criminals die when they get shot

**Comment by SmoSmoSmoSmok** [comment]
Criminla activity

**Review by SmoSmoSmoSmok — CHANGES_REQUESTED** [review]
Stop ignoring my suggestions

**Comment by Helianthus00** [comment]
I don't plan on merging this unless deputies are put into a state that fits Fulp better. Old deputies were not used correctly and were removed because nobody wanted to rework them. At the very least, deputies won't be re-added exactly as they were removed.

**Comment by Pepsilawn** [comment]
> I don't plan on merging this unless deputies are put into a state that fits Fulp better. Old deputies were not used correctly and were removed because nobody wanted to rework them. At the very least, deputies won't be re-added exactly as they were removed.

This can be worked on IM gonna be honest i hate the skillchip

**Comment by ReinaCoder** [comment]
ty please remove the block chance

**Comment by Pepsilawn** [comment]
i am back from estonia but id rather work on this at a later time

**Pull request closed without merging**
