### PR TITLE
You are no longer forced to play heliostation forever

### PR DESCRIPTION
**Pull request by Nobelium-XVIII**
## About The Pull Request
shuttle landing marker at evac was misplaced
## Why It's Good For The Game
yea
## Changelog
:cl:
fix: You are no longer forced to play heliostation forever
/:cl:

### CODE REVIEW

**Comment by SgtHunk** [comment]
hey man whats going on with mapdiffbot

**Comment by Nobelium-XVIII** [comment]
> hey man whats going on with mapdiffbot

it passed in 30 seconds

**Comment by SgtHunk** [comment]
whats fucked up is that my pr should've already fixed this

**Comment by Nobelium-XVIII** [comment]
i forgot to pull locally

**Pull request closed without merging**
