### PR TITLE
Adds DNA disk box to selene genetics lab

### PR DESCRIPTION
**Pull request by OneAsianTortoise**
## About The Pull Request
image
**Adds DNA disk box to selene genetics lab**

## Why It's Good For The Game
image

hey where's my admin role

I mean... uh... gene needs the disk I guess?

## Changelog

:cl:
fix: gives selene genetics lab the missing disk box, I guess.
/:cl:

### CODE REVIEW

**Comment by ReinaCoder** [comment]
erm.. are you an admin ?

**Comment by OneAsianTortoise** [comment]
> erm.. are you an admin ?

yea. i also have merge perm. real

**Comment by SgtHunk** [comment]
if i had merge perms i'd close this PR because you're not an admin

**Comment by OneAsianTortoise** [comment]
> if i had merge perms i'd close this PR because you're not an admin

k cry with ur tm perms

**Pull request merged**
