### PR TITLE
December TGU

### LINKED ISSUE #868: pubby virology has 2 disposals
## Reproduction:

image

It blocks access to the pandemic

### PR DESCRIPTION
**Pull request by FernandoJ8**
## About The Pull Request

Something something coffee, something something raid shadow legends

Now fixes #868

### CODE REVIEW

**Comment by FernandoJ8** [comment]
Let's see what the CI thinks

**Comment by OneAsianTortoise** [comment]
Die

**Comment by Pepsilawn** [comment]
All checks succesful!

**Comment by KittyNoodle** [comment]
This tgu is a tgu 👍

**Comment by SgtHunk** [comment]
fucked up if you think about it

**Pull request merged**
