### PR TITLE
Overhauls Selene's perma to have restaurant bots

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

The Warden forgot to check in on Selene's perma prisoners... for years! Maybe next time Nanotrasen shouldn't have the permabrig be on its completely separate sat!

Selenestation now has a new, abandoned, Prison wing, coming with lizard food, and lizard/rat bots, the only people willing to actually enter this hellhole, though the hole (portal, whatever) isn't big enough to allow prisoners to escape, it does allow them to make money so they can afford to buy food for themselves via the Chef console.

newseleneperma

## Why It's Good For The Game

I cant wait to play my favorite Space Station 13 map
image

## Changelog
:cl:
add: [Selene] Prison Wing has been completely overhauled and now has restaurant bots! Enjoy serving a lizard, or rat.
/:cl:

### CODE REVIEW

**Comment by Sheits** [comment]
lizard robot doesn't hiss

**Comment by JohnFulpWillard** [comment]
> 
> 
> lizard robot doesn't hiss

ok cry

**Comment by Helianthus00** [comment]
I really do not like this redesign. I'm fine adding the kitchenbots, and removing some of the cells to make more room for them is fine, but I'd prefer if you stay to the original design rather than a complete remapping of it.

**Comment by Sheits** [comment]
Yeah, also, if youre gonna make it hard to enter/exit you should add something like the chute meta has to let prisoners in

**Comment by JohnFulpWillard** [comment]
re-doing it in #313

**Pull request closed without merging**
