### PR TITLE
fixe s lighting glitch in pubystation ai sat

### PR DESCRIPTION
**Pull request by SmoSmoSmoSmok**
## About The Pull Request

the guy said i can pr it

## Changelog

:cl:

### CODE REVIEW

**Comment by Sheits** [comment]
awesome changelog

**Comment by Nobelium-XVIII** [comment]
Smokey your changelog pleas3

**Comment by Lyn505** [comment]
Changelog. That is all. :fu:

**Comment by SmoSmoSmoSmok** [comment]
so . sry i forgo

**Pull request merged**
