### PR TITLE
pubby atmos fix

### PR DESCRIPTION
**Pull request by Sadboysuss**
## About The Pull Request

adds layer manifolds to pubby atmos for sending to pure, also fixes the weird air mix pipes

## Why It's Good For The Game

pubby atmos doesn't have layer manifolds and it's annoying, with this PR it will have them

## Changelog
:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
sound: added/modified/removed audio or sound effects
image: added/modified/removed some icons or images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by Sadboysuss** [comment]
idk how to github I just added some map stuff

**Comment by SgtHunk** [comment]
PRing from master 💀

**Comment by OneAsianTortoise** [comment]
> PRing from master 💀

Respect tbh

**Comment by Horatio22** [comment]
You have outdated versions of both Pubby and Helio (if you look at the departure area for helio, you can see that this PR reverts the recent changes). Station map files won't know not to update the whole map, so if something is different than the current version, it will revert those changes. You'll need to re-submit this with updated maps and their own a fork (not from master). 

Also, please make a separate PR for each map for edits like this.

**Pull request closed without merging**
