### PR TITLE
Modsuit & ERT code improvements

### LINKED ISSUE #680: Fulp MODsuits don't work
## Reproduction:

1) Try to use a Fulp MODsuit
2) Doesn't work
- Fulp ERTs also don't work because of this.
- - Except safety moth since they don't have MODsuits.

### PR DESCRIPTION
**Pull request by Pepsilawn**
## About The Pull Request

They work now.

Fixes #680
Alternative to part of #684

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
Certified https://github.com/fulpstation/fulpstation/pull/641#issuecomment-1125680829 moment

**Comment by Pepsilawn** [comment]
Issue wasnt made until yesterday?

**Comment by Pepsilawn** [comment]
If anything its even easier to maintain now that MOD_ICON_OVERRIDE was added as a define vs how I previously had to reassign all the parts' icons to use our paths

**Comment by JohnFulpWillard** [comment]
> If anything its even easier to maintain now that MOD_ICON_OVERRIDE was added as a define vs how I previously had to reassign all the parts' icons to use our paths

When was the last time this was used?

**Comment by Pepsilawn** [comment]
> When was the last time this was used?

code/modules/mod/mod_control.dm ur welcome

**Pull request merged**
