### PR TITLE
Heliostation Patch 3 - Bridge Rework; Medical Maint Revamp; Minor Fixes 

### PR DESCRIPTION
**Pull request by OneAsianTortoise**
## About The Pull Request

**#Ready#**

**Merge #956 before merging this PR.**

The main purpose of bridge rework is to fix some of issues that has been around within heliostation bridge; such as captain and hop office being fully exposed to space or EVA not having shutter, while giving it a new look.

In the meantime, medical maint is revamped with new look and couples new maint rooms. It is also now connecting to bridge hallway.

Some of the wall disposal pipes are also removed in the area I reworked.

<details>
<summary>Before</summary>

</details>

<details>
<summary>After</summary>

</details>

## Changelog
:cl:
add: new heliostation bridge
fix: removes some of wall disposal pipes
/:cl:

### CODE REVIEW

**Comment by OneAsianTortoise** [comment]
Update brig maint entirely. 
Solar made by @SgtHunk 

image

**Comment by OneAsianTortoise** [comment]
New AI upload
image

**Comment by nintyuk** [comment]
When I played last week I ran in to issues with the north solars not wanting to connect to the console. I had to dismantle the console and put a wire under it to get the solars to connect

**Comment by OneAsianTortoise** [comment]
> When I played last week I ran in to issues with the north solars not wanting to connect to the console. I had to dismantle the console and put a wire under it to get the solars to connect

Thank you for putting the issue on the PR page. I will check it when I am available.

**Comment by OneAsianTortoise** [comment]
All reported bug fixed.

**Pull request merged**
