### PR TITLE
Re-adds erp  

### PR DESCRIPTION
**Pull request by Sheits**
## About The Pull Request

The removal of the kiss emote was originally a result of poor player behaviour, which is a moderation issue not a code issue. Now it has an actual use (kissing food) it feels unnecessary to have to edit it out of the game.

## Changelog

:cl:
add: You can now use the kiss emote
/:cl:

### CODE REVIEW

**Comment by Masebot1** [comment]
finally

**Comment by khevy** [comment]
*kiss

**Comment by Horatio22** [comment]
I can get on board with re-adding the kiss emote since it now has an actual function (and we can always re-remove it if it causes issues), but I don't particularly see the value of re-adding double beds.

**Review by Horatio22 — CHANGES_REQUESTED** [review]
This won't be considered with double beds included.

**Comment by Sheits** [comment]
done

**Review by Horatio22 — APPROVED** [review]

**Comment by JohnFulpWillard** [comment]
The emote had a function since January 10 2022 lol

Also I did bring up the "code-issue" thing in my original PR
image

**Pull request merged**
