### PR TITLE
[MDB IGNORE] Remaps Selene Science

### PR DESCRIPTION
**Pull request by aaaa1023**
## About The Pull Request

 Completely remaps Selene Science and maintenance around it. Pictures below:

<details>
  <summary>Genetics Lab with hallway desk</summary>
  
  image
</details>

<details>
  <summary>Robotics and Mech bay</summary>
  
  image 
</details>

<details>
  <summary>Main R&D desk</summary>
  
image
</details>

<details>
  <summary>Xenobiology and Cytology Satellite</summary>
  
  xen 
</details>

<details>
  <summary>Security Office, RD Office, and Research Server Room</summary>
  
  servers
</details>

<details>
  <summary>Circuits and Experiment Lab</summary>
  
  
xlab

</details>

<details>
  <summary>Ordnance Labs</summary>
  
   
olab

</details>

<details>
  <summary>Ordnance Launch and Test Site</summary>
  
  
boom

</details>

<details>
  <summary>Full Overview</summary>
  
  
full

</details>

I tried to test and make sure things worked but i'm sure I missed something somewhere.

## Why It's Good For The Game

- Selene science went mostly untouched for like a year and is visually really boring and pretty much only uses white tiles and purple tile corners.
- Genetics didn't have a front desk so you weren't able to ask easily for mutations.
- Medical Maintenance wasn't connected to Science Maintenance so you'd have to go through the main halls to get to science maintenance and it was a dead end for people without science access.

### CODE REVIEW

**Comment by OneAsianTortoise** [comment]
image
Should there be a scrubber here so it matches with the vent next to it and the scrubber below.
I don't know.

**Comment by Pepsilawn** [comment]
image

**Comment by Sheits** [comment]
> Oh boy. I don't have time to fully review this right now but I hate smartpipes with a passion and I'm going to ask that you use directional pipes instead. I'll look at this more in-depth likely sunday.

...why?

**Comment by Helianthus00** [comment]
> > Oh boy. I don't have time to fully review this right now but I hate smartpipes with a passion and I'm going to ask that you use directional pipes instead. I'll look at this more in-depth likely sunday.
> 
> ...why?

because it's my map and I don't want it to look like shit. Smartpipes clutter the map view and make it hard to see much of anything. You're free to use them on the other fulp maps but I will maintain directional pipes on my maps as long as they exist.

**Comment by SgtHunk** [comment]
> Smartpipes clutter the map view and make it hard to see much of anything

**Comment by aaaa1023** [comment]
think the merge conflicts are fixed

**Review by Helianthus00 — APPROVED** [review]

**Comment by Helianthus00** [comment]
I'm a little confused at some of the decisions here but I'm willing to give it a go. I might make some minor changes if I ever have motivation to map again. Things look functional as far as I have checked.

**Pull request merged**
