### PR TITLE
[READY] Ports old moth sprites.

### PR DESCRIPTION
**Pull request by StoneMason**
## About The Pull Request

Ports 4 moth sprites from the old repo, separating the wings from the antennae, in accordance with /tg/.

## Why It's Good For The Game

ec5383d39ffb55b70850a8adeea4e16e

## Changelog
:cl: Tuyi/Papaporo Paprito
add: Re-adds 4 moth sprites.
code: Added some lines in 'fulp_modules' to separate wings and antennae.

/:cl:

### CODE REVIEW

**Comment by StoneMason** [comment]
eyo this shit not [READY] hol up

**Comment by JohnFulpWillard** [comment]
absolutely winning

**Comment by StoneMason** [comment]
LET'S FUCKING GOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by ATH1909** [comment]
image

**Comment by StoneMason** [comment]
I'll just give the sprites a lil touch up on the weekend then.

**Comment by StoneMason** [comment]
That should make it not have gaps when dismembered. I'll give the sprites a touch to make it darker (like they did in the fix) when I finish the markings to go with the wings (I'll do that on another PR). For now, PR should be good to go. I hope.

7fd608746abe835286074515ef89f52f

**Pull request merged**
