### PR TITLE
New engineering bounties

### PR DESCRIPTION
**Pull request by BootlegBow**
## About The Pull Request

Adds some new engineering bounties
## Why It's Good For The Game

Your bounties are shit and I thought your engineering players might want this

## Changelog
:cl:
add: new engineering bounties
/:cl:

### CODE REVIEW

**Comment by BootlegBow** [comment]
my incompetence knows no bounds and i fucked up a merge commit

**Comment by SgtHunk** [comment]
Why not do this upstream?

**Comment by BootlegBow** [comment]
> Why not do this upstream?

TG banned me from their repo

**Comment by SgtHunk** [comment]
> TG banned me from their repo

Maybe don't shitpost on their repo next time
These changes could perfectly be done upstream, that you got banned for making meme PRs for the funny is on you

**Comment by JohnFulpWillard** [comment]
> Your bounties are shit

ow

**Comment by BootlegBow** [comment]
> > TG banned me from their repo
> 
> Maybe don't shitpost on their repo next time
> These changes could perfectly be done upstream, that you got banned for making meme PRs for the funny is on you

alright then

**Pull request closed without merging**
