### PR TITLE
removes lattice

### PR DESCRIPTION
**Pull request by Pepsilawn**
image
image
image
Yes these purple parts are indeed walls that are filtered out in strongdmm we have so many fucking lattices in our walls its incredible its ruining my gameplay why do we have so many lattices inside our walls even tg maps have them they're not visible or anything they're not intended yet no one's doing anything about it whats up with that

### CODE REVIEW

**Comment by SgtHunk** [comment]
just remove the maps tbh

**Comment by Pepsilawn** [comment]
> just remove the maps tbh

its on tg too i saw like 6 of them on meta alone

**Comment by JohnFulpWillard** [comment]
man i wish this was merged

**Comment by JohnFulpWillard** [comment]
if it gets merged NOW though then it will conflict with TGU and I will be like >:(

**Comment by JohnFulpWillard** [comment]
this doesnt even remove them all ⛽

**Comment by Pepsilawn** [comment]
i forgot i pr'd this here after i went to tg to fix theirs

**Pull request closed without merging**
