### PR TITLE
Removes Beefmen's phobia

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

I've played beefman for about 2 days and every single round, at least 1 person has walked up to me and told me 'stranger' just to inconvenience me. I've even had someone follow me around for ~15 minutes just repeatedly saying it to me, and when I left they continued over the radio.

## Why It's Good For The Game

We're the only server with Beefman, and we still have usually 0-1 beefmen per round. Whenever there IS one, they constantly get people intentionally or accidentally triggering their phobia throughout the entire round, it just isn't fun to play as Beefman.

## Changelog
:cl:
del: Beefman's stranger phobia.
/:cl:

### CODE REVIEW

**Comment by Pepsilawn** [comment]
That was me saying it

**Comment by ATH1909** [comment]
bro this is an even more common phobia

**Comment by JohnFulpWillard** [comment]
> 
> 
> bro this is an even more common phobia

To be triggered or to obtain? My goal is to have it be triggered less.

**Comment by ATH1909** [comment]
image
image

**Comment by ATH1909** [comment]
enjoy getting triggered by people calling out a cult in xenobiology lmao

**Comment by Helianthus00** [comment]
I want to tm this before I think about merging this, as I'm not sure it's a great idea. Honestly I hate the phobia to begin with because people just metagame it to fuck with beefmen.

**Comment by Helianthus00** [comment]
I still want something added to replace this eventually but also I'm not going to make it right now anyway. Maybe a lesser version of one of the current other traumas or something.

**Comment by FatCat919** [comment]
just take off your headset :trollface:

**Comment by Nobelium-XVIII** [comment]
grudgecode

**Pull request merged**
