### PR TITLE
Abandoned Research Outpost - Ashwalker Spawn

### PR DESCRIPTION
**Pull request by John-Dang**
## About The Pull Request
This introduces Nanotrasen Research Outpost Lambda, a camp that was established by the company after contract miners reported a strange signal from underground. They excavated it, and found a dormant tendril. Central Command ordered this facility built to monitor and study the sleeping structure, and to establish contact when it activated. Months and months passed, with the design of the facility and naturally formed grudges irritating the team of six as nothing happened. Eventually the lack of supplies and extensive damage from storms led to the company mothballing the facility as the employees finally left on a shuttle. Wouldn't it be funny if the tendril woke up just as they were leaving? Hah... anyways, this adds a new Ashwalker spawn. Unpowered, damaged, and balanced to the original spawn. There are machine boards, but no parts, and no lathe to print parts. If the ashwalkers want to make the machines, they'll need to either raid or trade with golems or the corporate miners.
image
image
image

## Why It's Good For The Game
Adds a fresh new spawn in addition to the other new ashwalkers spawn I made. More variety, more roleplay opportunity!

## Changelog
:cl:
add: Added Abandoned Research Outpost.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
Ash walkers have no way of doing plumbing for their sinks/showers. The /tg/ ash walker spawn gave them an infinite water puddle, what's the fix here?

**Comment by John-Dang** [comment]
> Ash walkers have no way of doing plumbing for their sinks/showers. The /tg/ ash walker spawn gave them an infinite water puddle, what's the fix here?

I'll add a puddle, thank you for notifying me!

**Comment by John-Dang** [comment]
The puddle has been added!
image

**Comment by Fikou** [comment]
cant they spawn at the same time as regular ash walkers

**Comment by Fikou** [comment]
also the outpost domes seem kinda bland and kinda busted, and using walls as corners looks really weird
image

**Comment by Helianthus00** [comment]
Like the other ashwalkers pr, these still edit /tg/ files. If you can't make it modular, I suggest a pr to /tg/station instead.

**Pull request closed without merging**
