### PR TITLE
Solitairestation2 Patch 1. Bug Fixes and Minor Improvement 

### PR DESCRIPTION
**Pull request by OneAsianTortoise**
## About The Pull Request

**List of Changes:**
- Adds fire alarm in arrival so players will not trap in arrival if firelock is on.
- Adds a window in medbay security outpost so sec/deputy can see the treatment room from his office. (I have to remove the fire extinguisher.)
- Adds privacy shutter on pharmacy counter too. (It was on window only, making the privacy shutter pointless.)
- Adds light in medbay SSD room. (It was dark)
- Removes the light on lawyer office airlock.
- Adjusts the positions of lights on security hallway. (So they match)
- Removes the floating light above lawyer office.
- Fixes seeing Booze-O-Mat through wall from teleporter room.
- Fixes cap office not bolting all the door when alarm goes off.
- Adds light in CE office. (It was dark)
- Adds light in service lathe room. (It was dark)
- Adds light in engineering security outpost. (It was dark)
- Fixes the missing decal in engineering lobby
- Adds light in the hallway to SM. (It was dark)
- Fixs telecomms temp control unit not being on.
- Fixs RnD server temp control unit not being on.
- Replace SM cooling loop orange pipe with pump.
- Adds a bit decal to telecomm room outside.
- Fixes the Atmospherics room oxygen decal
- Fixes turbine room tiles colour
- Removes firelock in RnD server room, so it will not set off shift-start.
- Adds light in the science lobby outside RnD server . (It was dark)
- Adds another xenobiology shield wall generator, making it a pair. (As it should be)
- Adds a firesafety closet to arrival

Overhauls EVA.

<details>
<summary>Before (Wrong Center Rack Decal / Ugly / I hate it)</summary>

</details>

<details>
<summary>After</summary>

</details>

Overhaul engineering storage

<details>
<summary>Before (Only 2 singlo shield. Look empty.)</summary>

</details>

<details>
<summary>After</summary>

</details>

**Overhaul gravity generator**

<details>
<summary>Before (WTF is this)</summary>

</details>

<details>
<summary>After</summary>

</details>

Overhaul xenobiology secured chamber

<details>
<summary>Before (Only 1 shield. Xeno can bust window to break shield. Disposal not working.)</summary>

</details>

<details>
<summary>After (I am not happy with it, but I am tired.)</summary>

</details>

**To fix:**
Cargo shuttle not fitting (FUCK)
Power grid shutting off SM filter, making SM goes BOOM (FUCK)
To improve:
Xeno lab decal. (It looks really plain)
AI sat is very vulnerable because half of the turrets are useless. (The Rwindow are literally blocking half of the turrets. You can kill AI by using teleporter, then you only need to break 1 turret to get to AI.)
Viro disposal leading to cargo.

## Why It's Good For The Game
I don't wanna let players experience Solitairestation1 again.

## Changelog

:cl:
I fix. I cry. I die.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
PR IT TO MY BRANCH NOT MASTER

**Comment by SmoSmoSmoSmok** [comment]
waht a dumbas

**Comment by OneAsianTortoise** [comment]
STFU I DIDN'T MEAN TO AS BR0IOPNWPIOGVHV4GTIOHW4GVREIOH34GTBERIOHPG3452IH00932G4R 

I AM FUCKING TIRED

**Comment by OperativeLyn** [comment]
😨

**Pull request closed without merging**
