### PR TITLE
(Most of) Command/Security can become Midround Bloodsuckers

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

They become a Bloodsucker through a Vampiric Accident, like how anyone can roll obsessed, anyone should be able to roll Bloodsuckers, minus some people that would be too OP to have.

### CODE REVIEW

**Comment by SpaceDragon00** [comment]
Just from a balance standpoint I think Sec Officer bloodsuckers would be way too easy, especially since many people are afraid to interfere with an "arrest" out of fear of being bwoinked. This isn't a problem with most other conversions, including vassalization, since all of sec can see they arent mindshielded, but I think the tools they get, the access they have, and the power they inherently hold via the rules would make this too easy to be fun for anyone, even the person playing

Im more fine with Dets and Brig Physes since theyre not supposed to be arresting anyways

**Comment by Helianthus00** [comment]
I wish there was some way to make these roles able to get it but at a much lower weight. I don't want command/sec bloodsuckers to be common but I think it is a good idea to make it possible. Could you make a second event for only them that is less common?

**Comment by JohnFulpWillard** [comment]
> I wish there was some way to make these roles able to get it but at a much lower weight. I don't want command/sec bloodsuckers to be common but I think it is a good idea to make it possible. Could you make a second event for only them that is less common?

The event only rolls max once per round, making it a second event would mean both the events could happen once per round, meaning 2 midround vamps at most

**Comment by Helianthus00** [comment]
After discussing this with the admin team, we're ok with the command being bloodsuckers but don't want to see security kept in here. If you cut it down to just command, this would work.

**Pull request closed without merging**
