### PR TITLE
Removes lightbulb on Pubbystation

### PR DESCRIPTION
**Pull request by JenniferWare**
## About The Pull Request
MY FIRST PR

### CODE REVIEW

**Comment by SmoSmoSmoSmok** [comment]
image
this 1 for context

**Comment by 567Turtle** [comment]
give me back my lightbulb i beg of you

**Comment by SgtHunk** [comment]
this map sucks

**Comment by SgtHunk** [comment]
i just realized why did it take 3 lines and not 1

wtf pubby uses old lights

**Pull request merged**
