### PR TITLE
Fulp map toxins are cursed

### PR DESCRIPTION
**Pull request by Ebb-Real**
## About The Pull Request

Adds the tank compressor to fulp maps, changes the color of the output pipes in helio also removes that weird second airlock button.

## Why It's Good For The Game

Fulp maps stay up to date and makes Helio toxins not weird.

## Changelog

:cl:
add: Adds the tank compressor to all fulp maps along with disks and modular computers.
fix: Removes duplicate airlock button.
qol: Makes helio toxins output pipes a different colour from input.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
fuck you

**Comment by Ebb-Real** [comment]
fuck you John fulp willard

**Comment by JohnFulpWillard** [comment]
revert solitaire changes, and heliostation is supposed to be on a freeze because of https://github.com/fulpstation/fulpstation/pull/508 conflicts

**Comment by Ebb-Real** [comment]
whats bad about the solitaire changes, also how do i know if somthing is on a freeze?

**Comment by Ebb-Real** [comment]
i'll just update this if toxins gets moved

**Comment by Ebb-Real** [comment]
how did it not break even though stuff was moved? Computers are smart.

**Comment by Ebb-Real** [comment]
reverting selene since #521 covers the selene thing

**Comment by OneAsianTortoise** [comment]
New ordnance probably is in next TGU. Maybe you should wait for it and update fulp map with new equipments too.

L

**Comment by Ebb-Real** [comment]
my PRs get fucked over every time by TG i swear

**Comment by Ebb-Real** [comment]
77% of this PR has ended up being useless cool

**Comment by Ebb-Real** [comment]
i can add the new toxins machine if it dosen't get added in TGU

**Comment by Ebb-Real** [comment]
Added the tank compresser to all fulp maps, a carp plushie to helio because carps always kill people there. Expanded selene launch room a bit to make room for it.

## Puppy:
image

## Helio:
image

## Selene:
image

**Comment by Ebb-Real** [comment]
i dunno how to make the expandable pics on github so now we just have a massive comment

**Comment by Ebb-Real** [comment]
should be good now

**Pull request merged**
