### PR TITLE
Cheaper living beefplushie and grammer fixes

### PR DESCRIPTION
**Pull request by Ebb-Real**
## About The Pull Request
Changes living beefplushie cost to 2 tc instead of 3 and fixes some bad grammer i did.

## Why It's Good For The Game

2 tc cost makes more sense when looking at the rest of the items, like healing smokes and will incentivize it to get used more.

## Changelog

:cl:
balance: The living beefplushie now costs 2 tc instead of 3.
spellcheck: Fixes living beefplushie grammer.
/:cl:

### CODE REVIEW

**Comment by StoneMason** [comment]
grammar*

**Comment by Ebb-Real** [comment]
> grammar*

image

**Comment by Greniza** [comment]
You're sure that it's not supposed to be 'simmilar', as in 'simmer', because beef pun?

**Comment by Ebb-Real** [comment]
a true pun not intended

**Pull request merged**
