### PR TITLE
Adds a cat plush.

### PR DESCRIPTION
**Pull request by Onadorable**
## About The Pull Request
This pull request brings the addition of a cat plush to the game.

## Why It's Good For The Game
The addition of this plush would be good for the community as it would improve morale for whenever somebody feels the need to hug a soft cat plush.

cat (2)

## Changelog

:cl:
add: Adds plushie_cat.dmi to plushes.dmi, and adds the code for it in plushes.dm
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
https://github.com/tgstation/tgstation

**Comment by SmoSmoSmoSmok** [comment]
i think yoy need to put the code in fulp_modules/features/toys/code/plushies.dm

**Comment by Onadorable** [comment]
> i think yoy need to put the code in fulp_modules/features/toys/code/plushies.dm

Thanks will do. I didn't know it had to be modular. Will remake when it's modular

**Comment by OneAsianTortoise** [comment]
Are... are you doing it on your master!? or I am being dum.

**Comment by Ebb-Real** [comment]
ye they are, you should thread it out of your master so you still have the original code. Also there's a draft button on the right side if you wanna make a PR "work in progress" and don't wanna close it so you can get code reviewed while you make it.

**Pull request closed without merging**
