### PR TITLE
Syndicate Engineers & The Prototype Station

### PR DESCRIPTION
**Pull request by Nobelium-XVIII**
## About The Pull Request

It's exactly as it says on the tin-- Syndicate Engineers are back!

0-added
(MDB render is a bit fucky but rest assured I fully tested it)
## Why It's Good For The Game

FulpStation is a beginner server, so having a space ruin dedicated to teaching new players the basics of engineering is... well, natural.
## Changelog
:cl:
add: Syndicate Engineer Ghost Role
add: Prototype Station Space Ruin
/:cl:

### CODE REVIEW

**Comment by Nobelium-XVIII** [comment]
don't worry about the integration tests it just means that not all items will be put back into the crate when you open & close it (which is a non-issue since there's 90% chance you use most of the items in it)

**Comment by Horatio22** [comment]
I like that the flavor text says that leaving is forbidden; is there a way to actually prevent them from leaving the z-level (maybe like the Russian station)?

**Comment by Nobelium-XVIII** [comment]
> I like that the flavor text says that leaving is forbidden; is there a way to actually prevent them from leaving the z-level (maybe like the Russian station)?

yeah i'll look into it-- probably will have to be done with an implant

**Comment by Nobelium-XVIII** [comment]
> I like that the flavor text says that leaving is forbidden; is there a way to actually prevent them from leaving the z-level (maybe like the Russian station)?

yeah they explode now

**Comment by Nobelium-XVIII** [comment]
the failed test is from something completely unrelated (a tongue failing to be GCed somehow??)

**Comment by Sadboysuss** [comment]
is this station from when SM wasn't a thing

**Comment by Nobelium-XVIII** [comment]
> is this station from when SM wasn't a thing

no, iirc it was custom-made for this ghost role back on the old fulp repo (from which I ported it from)

if you mean lore-wise, no idea

**Comment by Horatio22** [comment]
> they explode now

PERFECT.

**Pull request merged**
