### PR TITLE
Adds list of all TG edits our repo causes

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Latest TGU deleted a ton of TG edits we had, breaking a ton of our features.

### CODE REVIEW

**Comment by Nobelium-XVIII** [comment]
NOOOO NOT THE DIGI SHOES

**Comment by SgtHunk** [comment]
now do it in alphabetical order ((((or im going to go insane))))

**Comment by JohnFulpWillard** [comment]
> 
> 
> NOOOO NOT THE DIGI SHOES

How about next time you make it actually good?

**Review by SgtHunk — APPROVED** [review]
:trollface:

**Review by SgtHunk — COMMENTED** [review]
code/modules should go below code/games, also preferences_savefile and preferences are mentioned twice, IMO it should be only mentioned once with the description of both changes.

**Comment by JohnFulpWillard** [comment]
> 
> 
> code/modules should go below code/game

Fuck you

**Pull request merged**
