### PR TITLE
SeleneStation : Changed the morgue doors

### PR DESCRIPTION
**Pull request by EIB0N**
## About The Pull Request

Changed the morgue doors

## Why It's Good For The Game

Mapping standards I guess

## Changelog
:cl:
fix: Changed the morgue doors
/:cl:

### CODE REVIEW

**Comment by Horatio22** [comment]
Why'd you change it from chapel access to maint tunnel access?

**Comment by EIB0N** [comment]
> Why'd you change it from chapel access to maint tunnel access?

The area isn't the chapel, 12 uses maint tunel which is also the req used in helio it is connected to the maint why was the door 22 before?

**Comment by SgtHunk** [comment]
> > Why'd you change it from chapel access to maint tunnel access?
> 
> The area isn't the chapel, 12 uses maint tunnel which is also the req used in helio it is connected to the maint idk why it was 22 before 

Chaplains are allowed to go into the morgue in most maps (probably to fulfill their funny gimmick that involves corpses)

**Comment by EIB0N** [comment]
> > > Why'd you change it from chapel access to maint tunnel access?
> > 
> > 
> > The area isn't the chapel, 12 uses maint tunnel which is also the req used in helio it is connected to the maint idk why it was 22 before
> 
> Chaplains are allowed to go into the morgue in most maps (probably to fulfill their funny gimmick that involves corpses)

they are now allowed in the morgue

**Pull request merged**
