### PR TITLE
[Ready]Heliostation cargo shuttle change

### PR DESCRIPTION
**Pull request by EIB0N**
## About The Pull Request

- Changes the shuttle path code in heliostation.json located in \ _maps

old:
> "cargo": "cargo_box" 

new:
>"cargo":"cargo_helio"
 
- Adds new shuttle file named "cargo_helio.dmm" to the \_maps\shuttles folder

- Adds the following lines to the shuttles.dm file located in \code\datums:
>"/datum/map_template/shuttle/cargo/helio
>suffix = "helio"
>name = "cargo ferry (Helio)"

- Reduced the "height" variable from "/obj/docking_port/mobile/supply" and "/obj/docking_port/stationary" from 7 to 6

## Why It's Good For The Game
Allows for full control of changes to Heliostation cargo shuttle without dealing with ports from TG potentially causing conflict. It is also better than the previous one since the conveyers work properly and it has levers on the inside to control it all. 

## Changelog
🆑
add: New cargo shuttle for HelioStation with working levers and conveyer belts!
/🆑

Here it is in HelioStation
download

Here it is in Centcom
download

### CODE REVIEW

**Comment by remove32** [comment]
can you supply an image of it at the cargo dock at helio and at the dock at centcom?

**Comment by EIB0N** [comment]
Yup, my bad

**Comment by Helianthus00** [comment]
This has my approval. Better than the backwards conveyors on the current shuttle that I never figured out how to fix anyway.

**Comment by remove32** [comment]
tested this. @Helianthus00 you good with this?
image

**Comment by Helianthus00** [comment]
> tested this. only thing that stands out is the inside of the shuttle is lacking buttons to open the unloading doors.
> @Helianthus00 you good with this?
> image

Yep, I like it.

**Pull request merged**
