### PR TITLE
Protect HoP from antag roles

### LINKED ISSUE #54: HoP shouldn't be able to roll antag
Seems like this worked on the old repo. Need it ported

### PR DESCRIPTION
**Pull request by urococt**
## About The Pull Request

Adds Head of Personnel to `protected_jobs` wherever Security Officer is present.

I didn't test this since ~I am lazy~ the changes are so minor.

## Why It's Good For The Game

Resolves #54

## Changelog
:cl:
tweak: HoP is no longer eligible for most antag roles
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
cringe

**Comment by ATH1909** [comment]
Do note that /tg/ has recently merged a massive nerf to handing out AA en masse, which should make antagonist HoPs less disruptive to the round at large after you next resync with them: https://github.com/tgstation/tgstation/pull/56910.

**Comment by JohnFulpWillard** [comment]
Do it the same way it’s done with Brig doc in #16, rather than overwriting TG code

**Comment by Helianthus00** [comment]
With the coming changes, we would like to see how trimmed IDs help this issue. Holding on merging this until then.

**Pull request closed without merging**
