### PR TITLE
Fixes pubby's yellow stripes decal corner being weird and stuff

### PR DESCRIPTION
**Pull request by OneAsianTortoise**
## About The Pull Request
what

This is just some of them, I am not going to post all of them. 

## Why It's Good For The Game
I don't know. 

## Changelog

:cl:
fulp doesn't have changelog, no?
/:cl:

### CODE REVIEW

**Comment by SgtHunk** [comment]
i hope u used a script for this lol

**Comment by OneAsianTortoise** [comment]
> i hope u used a script for this lol

no i am dum i do it dum way

**Review by OperativeLyn — CHANGES_REQUESTED** [review]
You missed that one in engineering, bottom right.
image
And another one in ordnance storage.
image

**Comment by SgtHunk** [comment]
> man, does that mean I have to re-do it with script now

No but you missed some because you did it manually
@ contributors if you need help with setting up the update path script

**Comment by Helianthus00** [comment]
Doing things manually is the chad way

**Pull request merged**
